// grammar.js — Complete German Grammar section

export const grammarLessons = [
  { de: '═══════════════════════════════\nክፍል 1: መስተዋድድ — Articles\n(Der, Die, Das)\n═══════════════════════════════', am: 'በጀርመንኛ ሁሉም ስም (Noun) ጾታ አለው: **ተባዕታይ** (Maskulin), **አንስታይ** (Feminin), ወይም **መካከለኛ** (Neutrum)። ይህ ደንብ ማስታወስ አለበት — ምንም ሎጂክ የለውም ብዙ ጊዜ!!\n\n**Pro Tip:** ጀርመንኛ ሲማሩ ቃልን ብቻ ሳይሆን ከ Article ጋር ያስታውሱ! "Tisch" ብቻ ሳይሆን "der Tisch" ብለው ይማሩ!!!' },

  { de: '• der — ተባዕታይ (Masculine)', am: '**Der** ለተባዕታይ ስሞች ይጠቅማል:\n\n| ጀርመንኛ | ትርጉም |\n|---------|--------|\n| der Mann | ሰውየው |\n| der Tisch | ጠረጴዛው |\n| der Stuhl | ወንበሩ |\n| der Hund | ውሻው |\n| der Tag | ቀኑ |\n| der Morgen | ጥዋቱ |\n| der Abend | ማታው |\n| der Monat | ወሩ |\n| der Berg | ተራራው |\n| der Fluss | ወንዙ |\n\n**Pro Tip:** ብዙ ጊዜ ተባዕታይ የሆኑ ቃላት:\n• ቀኖች: der Montag, der Dienstag...\n• ወራት: der Januar, der Februar...\n• ወቅቶች: der Frühling, der Sommer...\n• የመኪና ብራንዶች: der BMW, der Mercedes\n• "-er" ደርሰት: der Lehrer, der Computer\n• "-ling" ደርሰት: der Frühling, der Schmetterling' },

  { de: '• die — አንስታይ (Feminine)', am: '**Die** ለአንስታይ ስሞች ይጠቅማል:\n\n| ጀርመንኛ | ትርጉም |\n|---------|--------|\n| die Frau | ሴቲቱ |\n| die Blume | አበባው |\n| die Schule | ት/ቤቱ |\n| die Katze | ድመቷ |\n| die Straße | ጎዳናው |\n| die Kirche | ቤተክርስቲያን |\n| die Musik | ሙዚቃው |\n| die Arbeit | ሥራው |\n| die Liebe | ፍቅር |\n| die Stadt | ከተማው |\n\n**Pro Tip:** ብዙ ጊዜ አንስታይ የሆኑ ቃላት:\n• "-e" ደርሰት: die Lampe, die Tasche\n• "-ung" ደርሰት: die Zeitung, die Wohnung\n• "-heit" ደርሰት: die Freiheit, die Gesundheit\n• "-keit" ደርሰት: die Möglichkeit\n• "-schaft" ደርሰት: die Freundschaft\n• "-tion" ደርሰት: die Information, die Nation' },

  { de: '• das — መካከለኛ (Neuter)', am: '**Das** ለመካከለኛ ስሞች ይጠቅማል:\n\n| ጀርመንኛ | ትርጉም |\n|---------|--------|\n| das Kind | ልጁ |\n| das Buch | መጽሐፉ |\n| das Haus | ቤቱ |\n| das Auto | መኪናው |\n| das Wasser | ውሃው |\n| das Brot | ዳቦው |\n| das Land | ሀገሩ |\n| das Mädchen | ልጃገረድ |\n| das Fenster | መስኮቱ |\n| das Telefon | ስልኩ |\n\n**Pro Tip:** ብዙ ጊዜ መካከለኛ የሆኑ ቃላት:\n• "-chen" ደርሰት: das Mädchen, das Brötchen\n• "-lein" ደርሰት: das Büchlein\n• "-ment" ደርሰት: das Dokument\n• "-um" ደርሰት: das Studium, das Museum\n• ብዙ ፊደላት: das Ge- : das Gebäude, das Gespräch\n\n⚠️ ትኩረት: "das Mädchen" (ልጃገረድ) መካከለኛ ነው ምንም እንኳን ሴት ብትሆንም — ምክንያቱ "-chen" ደርሰት ሁልጊዜ መካከለኛ ስለሆነ!!' },

  { de: '═══════════════════════════════\nክፍል 2: ኬዞች — Cases\n(Nominativ, Akkusativ, Dativ, Genitiv)\n═══════════════════════════════', am: 'ጀርመንኛ 4 "ኬዞች" (Cases) አሉት — ይህ ማለት Article እና ቅጽል (adjective) ቅርጻቸው ይቀየራል ስሙ በዓረፍተ ነገር ውስጥ ያለውን ሚና ለማሳየት ነው።\n\n**Pro Tip:** ይህ ክፍል ጀርመንኛ ሰዋስው ውስጥ በጣም አስፈላጊ ነው! ግን አይደነግጡ — ደረጃ ደረጃ ይማሩት!!!' },

  { de: '1. Nominativ (ባለቤት — Subject)', am: '**Nominativ** = ማን/ምን ነው ሥራውን የሚሰራው?\n\n| Article | ተባ. | አንስ. | መካ. | ብዙ |\n|---------|------|-------|------|------|\n| Bestimmt | der | die | das | die |\n| Unbestimmt | ein | eine | ein | — |\n\nምሳሌ:\n• **Der Mann** liest ein Buch. = ሰውየው መጽሐፍ ያነባል\n• **Die Frau** kauft Brot. = ሴቲቱ ዳቦ ትገዛለች\n• **Das Kind** spielt. = ልጁ ይጫወታል\n\n**Pro Tip:** Nominativ ሁልጊዜ ለ Subject (ባለቤት) ይጠቅማል — "ማን" የሚለውን ጥያቄ ይመልሳል። ይህ ቀላሉ case ነው!!' },

  { de: '2. Akkusativ (ተሠርቶበት — Direct Object)', am: '**Akkusativ** = ምንን/ማንን? (የተደረገበት ነገር)\n\n| Article | ተባ. | አንስ. | መካ. | ብዙ |\n|---------|------|-------|------|------|\n| Bestimmt | **den** | die | das | die |\n| Unbestimmt | **einen** | eine | ein | — |\n\n⚠️ ልዩነት: ተባዕታይ ብቻ ይቀየራል! der → den, ein → einen\n\nምሳሌ:\n• Ich sehe **den Mann**. = ሰውየውን አየሁ\n• Sie kauft **einen Tisch**. = ጠረጴዛ ትገዛለች\n• Wir essen **das Brot**. = ዳቦውን እንበላለን\n\n**Pro Tip:** Akkusativ ለ Direct Object (ቀጥተኛ ተሠርቶበት) ይጠቅማል — "ምንን/ማንን" የሚለውን ጥያቄ ይመልሳል። ተባዕታይ ብቻ ይቀየራል ስለዚህ ቀላል ነው!!\n\nAkkusativ Prepositions:\n• durch (በ...ውስጥ/በኩል)\n• für (ለ...)\n• gegen (ላይ/ተቃራኒ)\n• ohne (ያለ)\n• um (ዙሪያ)' },

  { de: '3. Dativ (ተቀባይ — Indirect Object)', am: '**Dativ** = ለማን? (ተቀባይ)\n\n| Article | ተባ. | አንስ. | መካ. | ብዙ |\n|---------|------|-------|------|------|\n| Bestimmt | **dem** | **der** | **dem** | **den (+n)** |\n| Unbestimmt | **einem** | **einer** | **einem** | — |\n\nምሳሌ:\n• Ich gebe **dem Mann** ein Buch. = ለሰውየው መጽሐፍ እሰጣለሁ\n• Sie hilft **der Frau**. = ለሴቲቱ ትረዳለች\n• Wir danken **dem Kind**. = ልጁን እናመሰግናለን\n\n**Pro Tip:** Dativ ለ Indirect Object (ተቀባይ) ይጠቅማል — "ለማን" የሚለውን ጥያቄ ይመልሳል።\n\nDativ Prepositions:\n• aus (ከ...ውስጥ)\n• bei (ጋር/ቤት)\n• mit (ከ...ጋር)\n• nach (ከ...በኋላ/ወደ)\n• seit (ከ...ጀምሮ)\n• von (ከ...)\n• zu (ወደ)\n\nTrick: **AUS-BEI-MIT-NACH-SEIT-VON-ZU** — ይህንን ደርድሩ ያስታውሱ!!!' },

  { de: '4. Genitiv (ባለቤትነት — Possession)', am: '**Genitiv** = የማን? (ባለቤትነት)\n\n| Article | ተባ. | አንስ. | መካ. | ብዙ |\n|---------|------|-------|------|------|\n| Bestimmt | **des (+s/es)** | der | **des (+s/es)** | der |\n| Unbestimmt | **eines (+s/es)** | einer | **eines (+s/es)** | — |\n\nምሳሌ:\n• Das Auto **des Mannes** = የሰውየው መኪና\n• Die Tasche **der Frau** = የሴቲቱ ቦርሳ\n• Das Spielzeug **des Kindes** = የልጁ አሻንጉሊት\n\n**Pro Tip:** Genitiv ለባለቤትነት ይጠቅማል — "የማን" የሚለውን ጥያቄ ይመልሳል። ተባዕታይ/መካከለኛ ስም ላይ "-s" ወይም "-es" ይጨምራል!\n\nGenitiv ዛሬ ዛሬ ብዙ ጀርመኖች ንግግር ውስጥ አይጠቀሙም — ከ Dativ ጋር ይቀይሩታል!! ግን ጽሑፍ ውስጥ ግዴታ ነው!!!' },

  { de: '═══════════════════════════════\nክፍል 3: ግስ ውቅር — Verb Conjugation\n═══════════════════════════════', am: 'ጀርመንኛ ግሶች (Verbs) በርዕሰ ጉዳይ (Subject) መሰረት ይቀየራሉ — ይህ "Konjugation" (ግስ ውቅር) ይባላል።\n\n**Pro Tip:** ጀርመንኛ ግስ ሁልጊዜ ከ "-en" ወይም "-n" ደርሰት ጋር ይመጣል: "lernen" (መማር)፣ "spielen" (መጫወት)። ግሱን ለመቀየር ደርሰቱን ያስወግዱና አዲስ ደርሰት ያክሉ!!' },

  { de: '• sein (መሆን / to be)', am: '| ማን | ግስ |\n|-----|------|\n| ich | **bin** |\n| du | **bist** |\n| er/sie/es | **ist** |\n| wir | **sind** |\n| ihr | **seid** |\n| sie/Sie | **sind** |\n\nምሳሌ:\n• Ich **bin** Student. = ተማሪ ነኝ\n• Du **bist** schön. = ቆንጆ ነህ/ሽ\n• Er **ist** Arzt. = ሐኪም ነው\n• Wir **sind** Freunde. = ጓደኞች ነን\n\n**Pro Tip:** "sein" ልዩ (irregular) ግስ ነው — ሁሉንም ቅርጽ ማስታወስ ያስፈልጋል!! ልክ እንደ እንግሊዝኛ "am/is/are"።' },

  { de: '• haben (ማግኘት / to have)', am: '| ማን | ግስ |\n|-----|------|\n| ich | **habe** |\n| du | **hast** |\n| er/sie/es | **hat** |\n| wir | **haben** |\n| ihr | **habt** |\n| sie/Sie | **haben** |\n\nምሳሌ:\n• Ich **habe** ein Auto. = መኪና አለኝ\n• Du **hast** Recht. = ትክክል ነህ/ሽ\n• Sie **hat** zwei Kinder. = ሁለት ልጆች አሏት\n\n**Pro Tip:** "haben" ሁለተኛው በጣም ጥቅም ላይ የሚውል ግስ ነው!! Past tense ለመሥራትም ይጠቅማል (Perfekt)።' },

  { de: '• Regular Verbs (-en pattern)', am: '**መደበኛ ግስ ውቅር ደንብ:**\n\nምሳሌ: **lernen** (መማር)\n\n| ማን | ደርሰት | ግስ |\n|-----|--------|------|\n| ich | -e | lern**e** |\n| du | -st | lern**st** |\n| er/sie/es | -t | lern**t** |\n| wir | -en | lern**en** |\n| ihr | -t | lern**t** |\n| sie/Sie | -en | lern**en** |\n\nተመሳሳይ ግሶች:\n• **spielen** (መጫወት): ich spiele, du spielst, er spielt...\n• **machen** (ማድረግ): ich mache, du machst, er macht...\n• **wohnen** (መኖር): ich wohne, du wohnst, er wohnt...\n• **kaufen** (መግዛት): ich kaufe, du kaufst, er kauft...\n• **fragen** (መጠየቅ): ich frage, du fragst, er fragt...\n\n**Pro Tip:** ይህ ደንብ 80%+ ጀርመንኛ ግሶች ላይ ይሠራል!! ደንቡን ካወቁ ብዙ ግስ ይቀይራሉ።' },

  { de: '• Stem-Changing Verbs (ልዩ ግሶች)', am: '**አንዳንድ ግሶች du/er/sie/es ላይ ሥር ይቀየራሉ:**\n\ne → i :\n• **sprechen** (መናገር): ich spreche, du **sprichst**, er **spricht**\n• **essen** (መብላት): ich esse, du **isst**, er **isst**\n• **geben** (መስጠት): ich gebe, du **gibst**, er **gibt**\n• **nehmen** (መውሰድ): ich nehme, du **nimmst**, er **nimmt**\n\ne → ie :\n• **lesen** (ማንበብ): ich lese, du **liest**, er **liest**\n• **sehen** (ማየት): ich sehe, du **siehst**, er **sieht**\n\na → ä :\n• **fahren** (መንዳት): ich fahre, du **fährst**, er **fährt**\n• **schlafen** (መተኛት): ich schlafe, du **schläfst**, er **schläft**\n• **tragen** (መሸከም): ich trage, du **trägst**, er **trägt**\n\n**Pro Tip:** እነዚህ ግሶች "Strong Verbs" ይባላሉ — ማስታወስ ያስፈልጋል!! ግን ጥቂት ብቻ ናቸው (ከ50 በታች)።' },

  { de: '• Modal Verbs (ረዳት ግሶች)', am: '**ረዳት ግሶች — ከሌላ ግስ ጋር ይጣመራሉ:**\n\n| ግስ | ትርጉም | ich | du | er |\n|-----|--------|-----|-----|-----|\n| können | መቻል | kann | kannst | kann |\n| müssen | ግዴታ | muss | musst | muss |\n| wollen | መፈለግ | will | willst | will |\n| sollen | ይገባል | soll | sollst | soll |\n| dürfen | ፈቃድ | darf | darfst | darf |\n| mögen | መውደድ | mag | magst | mag |\n\nምሳሌ:\n• Ich **kann** Deutsch **sprechen**. = ጀርመንኛ መናገር **እችላለሁ**\n• Du **musst** jetzt **gehen**. = አሁን መሄድ **አለብህ**\n• Wir **wollen** Kaffee **trinken**. = ቡና መጠጣት **እንፈልጋለን**\n\n**Pro Tip:** Modal verb ሁልጊዜ ሁለተኛ ቦታ ይይዛል፣ ዋናው ግስ (infinitiv) ወደ መጨረሻ ይሄዳል!!\n"Ich **kann** heute nicht **kommen**" = ዛሬ መምጣት **አልችልም**' },

  { de: '• Past Tense: Perfekt (ያለፈ ጊዜ)', am: '**Perfekt** = haben/sein + Partizip II\n\nRegular: ge- + stem + -t\n• machen → ge**mach**t (ሠራ)\n• spielen → ge**spiel**t (ተጫወተ)\n• kaufen → ge**kauf**t (ገዛ)\n\nIrregular: ge- + stem + -en (ሥር ይቀየራል)\n• essen → ge**gess**en (በላ)\n• trinken → ge**trunk**en (ጠጣ)\n• schreiben → ge**schrieb**en (ጻፈ)\n\nምሳሌ:\n• Ich **habe** Deutsch **gelernt**. = ጀርመንኛ ተማርኩ\n• Er **hat** Brot **gekauft**. = ዳቦ ገዛ\n• Sie **ist** nach Berlin **gefahren**. = ወደ በርሊን ሄደች\n\n**Pro Tip:** Movement ግሶች "sein" ይጠቀማሉ (gefahren, gegangen, geflogen)! ሌሎች "haben" ይጠቀማሉ!!\n\n⚠️ ትኩረት: "be-", "ver-", "er-" ቅድመ ቃል ያላቸው ግሶች "ge-" አይጨምሩም!\n• verstehen → verstanden (ተረዳ) — "ge-" የለም!!' },

  { de: '═══════════════════════════════\nክፍል 4: ዓረፍተ ነገር ግንባታ\n(Sentence Structure)\n═══════════════════════════════', am: 'ጀርመንኛ ዓረፍተ ነገር ግንባታ ከእንግሊዝኛ ይለያል — ግስ ሁልጊዜ ሁለተኛ ቦታ ላይ ይቆማል!!\n\n**Pro Tip:** ይህ ደንብ "V2 Rule" (Verb Second Rule) ይባላል — ጀርመንኛ ሰዋስው ቁልፍ ደንብ ነው!!!' },

  { de: '• Statement (መግለጫ ዓረፍተ ነገር)', am: '**ደንብ: ግስ = ቦታ 2**\n\n• **Ich** | **lerne** | Deutsch. = ጀርመንኛ እማራለሁ\n• **Heute** | **lerne** | ich Deutsch. = ዛሬ ጀርመንኛ እማራለሁ\n• **In Berlin** | **lerne** | ich Deutsch. = በርሊን ውስጥ ጀርመንኛ እማራለሁ\n\n**Pro Tip:** ያስተውሉ — ግስ ሁልጊዜ ሁለተኛ ቦታ ላይ ነው!! ቦታ 1 ላይ ማንኛውም ነገር ሊቆም ይችላል ግን ግስ ቦታ 2 ላይ ሁልጊዜ ቦታውን ይጠብቃል!!' },

  { de: '• Question (ጥያቄ)', am: '**Yes/No ጥያቄ: ግስ = ቦታ 1**\n• **Lernst** du Deutsch? = ጀርመንኛ ትማራለህ/ሽ?\n• **Sprechen** Sie Englisch? = እንግሊዝኛ ይናገራሉ?\n\n**W-ጥያቄ: W-ቃል + ግስ + ...**\n• **Was** lernst du? = ምን ትማራለህ?\n• **Wo** wohnst du? = የት ትኖራለህ?\n• **Wann** kommst du? = መቼ ትመጣለህ?\n• **Warum** lernst du Deutsch? = ለምን ጀርመንኛ ትማራለህ?\n• **Wie** heißt du? = ስምህ/ሽ ማን ነው?\n\n**Pro Tip:** W-ቃላት (Was, Wo, Wann, Warum, Wie, Wer, Wen, Wem) ያስታውሱ — ሁሉም ጥያቄ ይህ ይጀምራል!!' },

  { de: '• Negation (ክህደት)', am: '**"nicht" vs "kein":**\n\n**nicht** = ግስ/ቅጽል/ተውላጠ ቃል ለመካድ:\n• Ich komme **nicht**. = አልመጣም\n• Das ist **nicht** schön. = ቆንጆ አይደለም\n\n**kein/keine** = ስም (Noun) ለመካድ:\n• Ich habe **kein** Auto. = መኪና የለኝም\n• Er hat **keine** Zeit. = ጊዜ የለውም\n• Wir haben **keine** Kinder. = ልጆች የሉንም\n\n**Pro Tip:** "ein" ያለው → "kein" ይሆናል\n"ein Buch" → "kein Buch"\n"eine Frau" → "keine Frau"\n\nArticle የሌለው → "kein/keine" ይጨምራል\n"Ich habe Geld" → "Ich habe kein Geld"' },

  { de: '═══════════════════════════════\nክፍል 5: ቅጽሎች — Adjectives\n═══════════════════════════════', am: 'ጀርመንኛ ቅጽሎች (Adjectives) ከስም ፊት ሲመጡ case/gender መሰረት ደርሰት ይቀየራሉ!!\n\n**Pro Tip:** ቅጽል ብቻ ሲሆን ደርሰት አይቀየርም: "Der Mann ist **groß**"። ግን ከስም ፊት ሲሆን ይቀየራል: "Der **große** Mann"!!' },

  { de: '• Common Adjectives (ተለምዶ ቅጽሎች)', am: '| ጀርመንኛ | ትርጉም | ተቃራኒ |\n|---------|--------|--------|\n| groß | ትልቅ | klein (ትንሽ) |\n| alt | አሮጌ/ሽማግሌ | neu/jung (አዲስ/ወጣት) |\n| schnell | ፈጣን | langsam (ዝግ) |\n| gut | ጥሩ | schlecht (መጥፎ) |\n| heiß | ትኩስ | kalt (ቀዝቃዛ) |\n| teuer | ውድ | billig (ርካሽ) |\n| leicht | ቀላል | schwer (ከባድ) |\n| schön | ቆንጆ | hässlich (አስቀያሚ) |\n| lang | ረጅም | kurz (አጭር) |\n| stark | ጠንካራ | schwach (ደካማ) |\n\n**Pro Tip:** ተቃራኒ ቃላትን አብረው ይማሩ — ሁለት ቃል በአንድ ጊዜ!!' },

  { de: '• Comparative & Superlative', am: '**ንጽጽር — Comparisons:**\n\nRegular:\n• schnell → schnell**er** → am schnell**sten** (ፈጣን → ይበልጥ ፈጣን → በጣም ፈጣን)\n• klein → klein**er** → am klein**sten**\n\nWith Umlaut:\n• groß → größ**er** → am größ**ten** (ትልቅ → ይበልጥ ትልቅ → በጣም ትልቅ)\n• alt → ält**er** → am ält**esten**\n• jung → jüng**er** → am jüng**sten**\n\nIrregular:\n• gut → **besser** → am **besten** (ጥሩ → ይሻላል → ምርጥ)\n• viel → **mehr** → am **meisten** (ብዙ → ይበልጣል → በጣም ብዙ)\n• gern → **lieber** → am **liebsten** (ደስ ይላል → ይበልጥ ደስ → በጣም ደስ)\n\n**Pro Tip:** "als" = ከ... (comparison): "Berlin ist **größer als** München" = በርሊን ከሙኒክ **ይበልጣል**' },

  { de: '═══════════════════════════════\nክፍል 6: ቅድመ ቃላት — Prepositions\n═══════════════════════════════', am: 'ቅድመ ቃላት (Prepositions) ከ case ጋር ይጣመራሉ — አንዳንዶች Akkusativ፣ አንዳንዶች Dativ፣ አንዳንዶች ሁለቱም!!\n\n**Pro Tip:** "Wechselpräpositionen" (ተለዋጭ ቅድመ ቃላት) ከ movement = Akkusativ፣ ያለ movement = Dativ!!' },

  { de: '• Two-Way Prepositions (ተለዋጭ)', am: '**9 Wechselpräpositionen:**\n• **an** (ላይ/ዘንድ)\n• **auf** (ላይ)\n• **hinter** (ኋላ)\n• **in** (ውስጥ)\n• **neben** (ጎን)\n• **über** (ከላይ)\n• **unter** (ከታች)\n• **vor** (ፊት)\n• **zwischen** (መካከል)\n\n**Akkusativ (Movement/Wohin?):**\n• Ich gehe **in die** Schule. = ወደ ት/ቤት እሄዳለሁ\n\n**Dativ (Location/Wo?):**\n• Ich bin **in der** Schule. = ት/ቤት ውስጥ ነኝ\n\n**Pro Tip:** "Wohin?" (ወዴት?) = Akkusativ\n"Wo?" (የት?) = Dativ\nይህ ደንብ 9ቱም ላይ ይሠራል!!' },

  { de: '═══════════════════════════════\nክፍል 7: ተውላጠ ስሞች — Pronouns\n═══════════════════════════════', am: '**Personal Pronouns (ግላዊ ተውላጠ ስሞች):**\n\n| Nominativ | Akkusativ | Dativ | ትርጉም |\n|-----------|-----------|-------|--------|\n| ich | mich | mir | እኔ |\n| du | dich | dir | አንተ/ቺ |\n| er | ihn | ihm | እሱ |\n| sie | sie | ihr | እሷ |\n| es | es | ihm | ለ(መካከለኛ) |\n| wir | uns | uns | እኛ |\n| ihr | euch | euch | እናንተ |\n| sie/Sie | sie/Sie | ihnen/Ihnen | እነሱ/እርስዎ |\n\nምሳሌ:\n• Ich liebe **dich**. = እወድሃለሁ/ሻለሁ (Akkusativ)\n• Gib **mir** das Buch. = መጽሐፉን ስጠኝ (Dativ)\n• Können Sie **uns** helfen? = ሊረዱን ይችላሉ? (Dativ)\n\n**Pro Tip:** "Sie" (ትልቅ S) = እርስዎ (ፎርማል)፣ "sie" (ትንሽ s) = እሷ/እነሱ — ፊደል መጠን ትርጉም ይለውጣል!!' },

  { de: '═══════════════════════════════\nክፍል 8: ጠቃሚ ዓረፍተ ነገሮች\n(Useful Phrases)\n═══════════════════════════════', am: 'ለዕለት ተዕለት ንግግር ጠቃሚ ዓረፍተ ነገሮች:\n\n**Pro Tip:** እነዚህን ዓረፍተ ነገሮች ያስታውሱ — ጀርመን ውስጥ በየቀኑ ይጠቅማሉ!!' },

  { de: '• Everyday Phrases (የዕለት ዓረፍተ ነገሮች)', am: '• "Entschuldigung!" = ይቅርታ! / ጥያቄ ለመጠየቅ\n• "Wie bitte?" = ምን ብለው? (ያልገባዎት ጊዜ)\n• "Es tut mir leid." = ይቅርታ (ለስህተት)\n• "Macht nichts." = ምንም አይደለም\n• "Genau!" = ልክ!/ትክክል!\n• "Natürlich!" = በእርግጥ!\n• "Vielleicht." = ምናልባት\n• "Keine Ahnung." = ምንም ሀሳብ የለኝም\n• "Das ist toll!" = ጥሩ ነው!/ግሩም!\n• "Kein Problem." = ችግር የለም\n• "Bitte schön." = ምንም አይደለም / ይቅርታ (ከ"Danke" በኋላ)\n• "Stimmt!" = ልክ ነው!/ትክክል!\n• "Ich bin dran." = ተራዬ ነው\n\n**Pro Tip:** "Genau" ጀርመኖች በጣም ብዙ ይጠቀሙበታል — ልክ "okay" ወይም "exactly" እንደ ማለት!' },

  { de: '• Polite Requests (ትህትናዊ ጥያቄዎች)', am: '• "Können Sie mir helfen?" = ሊረዱኝ ይችላሉ?\n• "Darf ich...?" = ልዬ/ላድርግ...?\n• "Könnten Sie bitte...?" = ቢደረግ ይቻላል...?\n• "Ich hätte gern..." = ...እፈልጋለሁ (ትህትናዊ)\n• "Würden Sie bitte...?" = ...ቢያደርጉ?\n• "Wären Sie so nett...?" = ደግ ሆነው...?\n\n**Pro Tip:** "Könnten" (ከ können) እና "Würden" (ከ werden) ትህትና ያሳያል — ይህ "Konjunktiv II" ይባላል!! ጀርመን ውስጥ ትህትና = ፎርማል ቋንቋ!!!' },

  { de: '• Self-Introduction (ራስን ማስተዋወቅ)', am: '**Template:**\n• "Ich heiße [ስም]." = ስሜ [ስም] ነው\n• "Ich komme aus [ሀገር]." = ከ[ሀገር] ነኝ\n• "Ich bin [ዕድሜ] Jahre alt." = [ዕድሜ] ዓመቴ ነው\n• "Ich wohne in [ከተማ]." = [ከተማ] ውስጥ እኖራለሁ\n• "Ich bin [ሙያ] von Beruf." = ሙያዬ [ሙያ] ነው\n• "Ich spreche [ቋንቋ]." = [ቋንቋ] እናገራለሁ\n• "Ich lerne Deutsch." = ጀርመንኛ እማራለሁ\n\nምሳሌ:\n"Hallo! Ich heiße Agegnehu. Ich komme aus Äthiopien. Ich bin 24 Jahre alt. Ich wohne in Hantate. Ich lerne Deutsch."\n\n**Pro Tip:** ይህንን template በልብ ያስታውሱ — ጀርመን ሲደርሱ ብዙ ጊዜ ይጠቅማል!!!' },
];
