// vocabulary.js — 500+ themed vocabulary words with Pro Tips

export const travelVocabulary = [
  { de: '═══ በአውሮፕላን ጣቢያ (At the Airport) ═══', am: '✈️ የአውሮፕላን ጣቢያ ቃላት' },
  { de: 'der Flughafen', am: 'Airport / አውሮፕላን ጣቢያ\n\n**Pro Tip (ፕሮ ቲፕ):** "Flug" ማለት "በረራ"፣ "Hafen" ማለት "ወደብ" — ስለዚህ "Flughafen" = "የበረራ ወደብ" ማለት ነው። ጀርመንኛ ቃላትን በማጣመር አዳዲስ ቃላት ይፈጥራል — ይህ ባሕሪ "Compound Words" ይባላል።' },
  { de: 'das Flugzeug', am: 'Airplane / አውሮፕላን\n\n**Pro Tip:** "Zeug" ማለት "ነገር/መሣሪያ" — "Flugzeug" = "የበረራ መሣሪያ"። ተመሳሳይ: "Fahrzeug" = "የመንዳት መሣሪያ" = መኪና/ተሽከርካሪ።' },
  { de: 'der Pass / der Reisepass', am: 'Passport / ፓስፖርት\n\n**Pro Tip:** "Reise" = ጉዞ + "Pass" = ፓስ — "Reisepass" = "የጉዞ ፓስ"። ጀርመን ሲገቡ ፓስፖርትዎን ይዘው ይሂዱ — "Ihren Pass, bitte!" (ፓስፖርትዎን፣ እባክዎ!) ይባላሉ።' },
  { de: 'das Visum', am: 'Visa / ቪዛ\n\n**Pro Tip:** "Brauche ich ein Visum?" = "ቪዛ ያስፈልገኛል?" ብለው መጠየቅ ይችላሉ። ኢትዮጵያውያን ወደ ጀርመን ለመሄድ ቪዛ ያስፈልጋቸዋል።' },
  { de: 'der Koffer', am: 'Suitcase / ሻንጣ\n\n**Pro Tip:** "Ich habe meinen Koffer verloren" = "ሻንጣዬን አጥቻለሁ" — ይህ ዓረፍተ ነገር በአውሮፕላን ጣቢያ ጠቃሚ ነው።' },
  { de: 'die Bordkarte', am: 'Boarding pass / ቦርዲንግ ፓስ\n\n**Pro Tip:** "Bord" = "ጀልባ/መርከብ" (ከባሕር ቃላት የመጣ)። "Ihre Bordkarte, bitte" = "ቦርዲንግ ፓስዎን እባክዎ"።' },
  { de: 'der Abflug', am: 'Departure / መነሻ\n\n**Pro Tip:** "Ab" = "ከ..." + "Flug" = "በረራ" — "Abflug" = ከበረራ/መነሻ። ተቃራኒው "Ankunft" (መድረሻ) ነው።' },
  { de: 'die Ankunft', am: 'Arrival / መድረሻ\n\n**Pro Tip:** "An" = "ወደ" + "Kunft" (ከ "kommen" = መምጣት) — "Ankunft" = መድረስ/ደረሰ። ታቦሎዎች ላይ "Ankunft/Abflug" ይፃፋል።' },
  { de: 'das Gate / der Ausgang', am: 'Gate / በር\n\n**Pro Tip:** "Ausgang" = "ውጪያ/የወጪያ በር"። "Notausgang" = "የአደጋ ጊዜ በር" — ይህ ቃል ሁሉም ጀርመን ቤቶችና ሕንፃዎች ላይ ይገኛል።' },
  { de: 'die Passkontrolle', am: 'Passport control / ፓስፖርት ቁጥጥር\n\n**Pro Tip:** ጀርመንኛ ውስጥ ብዙ ቃላት "Kontrolle" ያበቃሉ: "Grenzkontrolle" = ድንበር ቁጥጥር፣ "Sicherheitskontrolle" = ደህንነት ቁጥጥር።' },
  { de: 'der Zoll', am: 'Customs / ጉምሩክ\n\n**Pro Tip:** "Haben Sie etwas zu verzollen?" = "የሚያስገቡት ነገር አለ?" — ጉምሩክ ላይ ይህ ይጠየቃሉ።' },
  { de: 'die Gepäckausgabe', am: 'Baggage claim / ሻንጣ ማንሻ ቦታ\n\n**Pro Tip:** "Gepäck" = ሻንጣ + "Ausgabe" = ማውጫ — ቃል በቃል "ሻንጣ ማውጫ" ማለት ነው።' },

  { de: '═══ በሆቴል (At the Hotel) ═══', am: '🏨 የሆቴል ቃላት' },
  { de: 'das Hotel', am: 'Hotel / ሆቴል\n\n**Pro Tip:** ጀርመን ውስጥ ሆቴሎች ከ1-5 ኮከብ ይመደባሉ። "Pension" ወይም "Gasthaus" ርካሽ አማራጮች ናቸው።' },
  { de: 'das Zimmer', am: 'Room / ክፍል\n\n**Pro Tip:** "Einzelzimmer" = ነጠላ ክፍል፣ "Doppelzimmer" = ድርብ ክፍል፣ "Familienzimmer" = የቤተሰብ ክፍል።' },
  { de: 'die Reservierung', am: 'Reservation / ቦታ ማስያዝ\n\n**Pro Tip:** "Ich habe eine Reservierung" = "ቦታ አስይዤአለሁ" — ሆቴል ሲደርሱ ይህ ዓረፍተ ነገር ይጠቅማል።' },
  { de: 'der Schlüssel', am: 'Key / ቁልፍ\n\n**Pro Tip:** "Zimmerschlüssel" = የክፍል ቁልፍ። "Ich habe meinen Schlüssel vergessen" = "ቁልፌን ረስቼዋለሁ"።' },
  { de: 'das Frühstück', am: 'Breakfast / ቁርስ\n\n**Pro Tip:** "Früh" = ቀደም ብሎ + "Stück" = ቁራሽ — "Frühstück" = "የቀደመ ቁራሽ"። ጀርመን ሆቴሎች ውስጥ ቁርስ ብዙ ጊዜ ዳቦ፣ ቀረሮ፣ ወተት ነው።' },
  { de: 'einchecken / auschecken', am: 'Check in / Check out\n\n**Pro Tip:** "Wann muss ich auschecken?" = "መቼ ነው ለመውጣት?" — ብዙ ጊዜ ከቀኑ 11:00 ወይም 12:00 ነው።' },
  { de: 'die Rechnung', am: 'Bill / ሂሳብ\n\n**Pro Tip:** "Die Rechnung, bitte!" = "ሂሳቡን እባክዎ!" — ይህ በሆቴልም በምግብ ቤትም ይጠቅማል።' },

  { de: '═══ ትራንስፖርት (Transportation) ═══', am: '🚌 የትራንስፖርት ቃላት' },
  { de: 'der Zug', am: 'Train / ባቡር\n\n**Pro Tip:** ጀርመን የባቡር ሥርዓት (Deutsche Bahn / DB) በዓለም ከሚታወቁት ውስጥ ነው። "ICE" = ፈጣን ባቡር፣ "RE" = ክልላዊ ባቡር።' },
  { de: 'der Bus', am: 'Bus / አውቶቡስ\n\n**Pro Tip:** "Bushaltestelle" = የአውቶቡስ ማቆሚያ። "Wann kommt der nächste Bus?" = "ቀጣዩ አውቶቡስ መቼ ይመጣል?"' },
  { de: 'die U-Bahn', am: 'Subway / ከመሬት በታች ባቡር\n\n**Pro Tip:** "U" = "Unter" (ከ...በታች)። "U-Bahn" = ከመሬት በታች ያለ ባቡር። "S-Bahn" = "Schnellbahn" (ፈጣን ባቡር) ከመሬት በላይ ነው።' },
  { de: 'die Straßenbahn', am: 'Tram / ትራም\n\n**Pro Tip:** "Straße" = ጎዳና + "Bahn" = ባቡር — ጎዳና ላይ የሚሄድ ባቡር ማለት ነው።' },
  { de: 'das Taxi', am: 'Taxi / ታክሲ\n\n**Pro Tip:** ጀርመን ታክሲዎች ነጭ ቀለም ናቸው። "Zum Flughafen, bitte!" = "ወደ አውሮፕላን ጣቢያ፣ እባክዎ!"' },
  { de: 'die Fahrkarte', am: 'Ticket / ቲኬት\n\n**Pro Tip:** "Fahrkarte" = "የመንዳት ካርድ"። "Einzelfahrkarte" = ነጠላ ቲኬት፣ "Tageskarte" = የቀን ቲኬት፣ "Monatskarte" = የወር ቲኬት።' },
  { de: 'der Bahnhof', am: 'Train station / ባቡር ጣቢያ\n\n**Pro Tip:** "Hauptbahnhof" (Hbf) = ዋና ባቡር ጣቢያ — ሁሉም ከተሞች ውስጥ ይገኛል። "Wo ist der Bahnhof?" = "ባቡር ጣቢያ የት ነው?"' },
  { de: 'die Haltestelle', am: 'Stop / ማቆሚያ\n\n**Pro Tip:** "Nächste Haltestelle" = "ቀጣይ ማቆሚያ" — ይህ በአውቶቡስና ትራም ውስጥ ይነገራል።' },
  { de: 'der Fahrplan', am: 'Schedule / የጊዜ ሰሌዳ\n\n**Pro Tip:** "Fahr" = መንዳት + "Plan" = ዕቅድ — ባቡርና አውቶቡስ ጣቢያ ላይ ታይቶ ይገኛል።' },
  { de: 'die Verspätung', am: 'Delay / መዘግየት\n\n**Pro Tip:** "Der Zug hat 10 Minuten Verspätung" = "ባቡሩ 10 ደቂቃ ዘግይቷል"። ጀርመኖች ለጊዜ ቅንጅት (Pünktlichkeit) ትልቅ ትኩረት ይሰጣሉ!!' },

  { de: '═══ አቅጣጫ መጠየቅ (Asking Directions) ═══', am: '🧭 አቅጣጫ መጠየቅ' },
  { de: 'Wo ist...?', am: 'Where is...? / ...የት ነው?\n\n**Pro Tip:** "Wo ist der Bahnhof?" = "ባቡር ጣቢያ የት ነው?" "Wo ist die Toilette?" = "ሽንት ቤት የት ነው?" — በጣም አስፈላጊ ዓረፍተ ነገር።' },
  { de: 'Wie komme ich zu...?', am: 'How do I get to...? / ወደ... እንዴት እሄዳለሁ?\n\n**Pro Tip:** "Wie komme ich zum Bahnhof?" = "ወደ ባቡር ጣቢያ እንዴት እሄዳለሁ?" "zu" + dem = "zum" (ለወንድ/መካከለኛ ስም)። "zu" + der = "zur" (ለሴት ስም)።' },
  { de: 'links / rechts / geradeaus', am: 'Left / Right / Straight ahead / ግራ / ቀኝ / ቀጥ ብሎ\n\n**Pro Tip:** "Gehen Sie geradeaus, dann links" = "ቀጥ ብለው ይሂዱ ከዛ ግራ"። ይህ ዓረፍተ ነገር ሰዎች ብዙ ጊዜ ይጠቀማሉ።' },
  { de: 'die Kreuzung', am: 'Intersection / መንገድ መገናኛ\n\n**Pro Tip:** "An der nächsten Kreuzung rechts" = "በቀጣይ መገናኛ ላይ ቀኝ" — ይህ የአቅጣጫ ተደጋጋሚ ዓረፍተ ነገር ነው።' },
  { de: 'die Ampel', am: 'Traffic light / ትራፊክ መብራት\n\n**Pro Tip:** "Bei der Ampel links abbiegen" = "ትራፊክ መብራት ላይ ግራ ማዞር"።' },
  { de: 'die Brücke', am: 'Bridge / ድልድይ\n\n**Pro Tip:** "Über die Brücke gehen" = "ድልድዩን ተሻግሮ መሄድ"።' },
  { de: 'gegenüber', am: 'Opposite / ፊት ለፊት\n\n**Pro Tip:** "Das Hotel ist gegenüber dem Bahnhof" = "ሆቴሉ ከባቡር ጣቢያ ፊት ለፊት ነው"።' },
  { de: 'neben', am: 'Next to / ቀጥሎ\n\n**Pro Tip:** "Die Apotheke ist neben dem Supermarkt" = "ፋርማሲው ከሱፐርማርኬት ቀጥሎ ነው"።' },
  { de: 'zwischen', am: 'Between / በ...መካከል\n\n**Pro Tip:** "Das Restaurant ist zwischen der Bank und dem Kino" = "ምግብ ቤቱ ባንክና ሲኒማ መካከል ነው"።' },

  { de: '═══ በምግብ ቤት (At the Restaurant) ═══', am: '🍽️ በምግብ ቤት' },
  { de: 'die Speisekarte', am: 'Menu / ሜኑ\n\n**Pro Tip:** "Die Speisekarte, bitte!" = "ሜኑውን እባክዎ!"' },
  { de: 'bestellen', am: 'To order / ማዘዝ\n\n**Pro Tip:** "Ich möchte bestellen" = "ማዘዝ እፈልጋለሁ"። "Ich hätte gerne..." = "...ቢሰጡኝ ደስ ይለኛል" (ተዛማጅ ግስ)።' },
  { de: 'das Wasser', am: 'Water / ውሃ\n\n**Pro Tip:** ጀርመን ውስጥ "Wasser" ብለው ብቻ ካዘዙ ጋዝ ያለው (Sprudel/mit Gas) ይመጣል! "Stilles Wasser" = ጋዝ የሌለው ውሃ ብለው መጠየቅ ያስፈልጋል።' },
  { de: 'das Bier', am: 'Beer / ቢራ\n\n**Pro Tip:** ጀርመን በቢራ ባህል ዝነኛ ናት — "Reinheitsgebot" (የንፅህና ሕግ) ከ1516 ዓ.ም ጀምሮ ነው!!' },
  { de: 'der Kaffee', am: 'Coffee / ቡና/ካፌ\n\n**Pro Tip:** ጀርመኖች ብዙ ቡና ይጠጣሉ! "Kaffee und Kuchen" (ቡናና ኬክ) ከሰዓት ቀጠሮ ልማድ ነው — ኢትዮጵያዊ የቡና ባህል ጋር ተመሳሳይ!!' },
  { de: 'das Trinkgeld', am: 'Tip / ጉርሻ\n\n**Pro Tip:** ጀርመን ውስጥ 5-10% ጉርሻ ሰርቭስ ላይ ማከል ልማድ ነው — ግን ግዴታ አይደለም። "Stimmt so!" = "ልዩነቱ ለአንተ ነው" (ጉርሻ ሲሰጡ)።' },
  { de: 'die Vorspeise', am: 'Appetizer / ቅርሱ ምግብ\n\n**Pro Tip:** "Vor" = ከ...በፊት + "Speise" = ምግብ — ከዋናው ምግብ በፊት የሚቀርብ ቀላል ምግብ።' },
  { de: 'die Hauptspeise', am: 'Main course / ዋና ምግብ\n\n**Pro Tip:** "Haupt" = ዋና + "Speise" = ምግብ — ዋናው የምግብ ዓይነት።' },
  { de: 'die Nachspeise / der Nachtisch', am: 'Dessert / ማጠቃለያ ምግብ\n\n**Pro Tip:** "Nach" = ከ...በኋላ + "Speise/Tisch" — ከዋናው ምግብ በኋላ የሚቀርብ ጣፋጭ።' },
  { de: 'vegetarisch / vegan', am: 'Vegetarian / Vegan\n\n**Pro Tip:** "Haben Sie vegetarische Gerichte?" = "ቬጀቴሪያን ምግብ አለዎት?" ጀርመን ውስጥ ብዙ ቬጀቴሪያን/ቪጋን ምግቦች ይገኛሉ።' },
  { de: 'die Allergie', am: 'Allergy / አለርጂ\n\n**Pro Tip:** "Ich habe eine Allergie gegen Nüsse" = "ለለውዝ አለርጂ አለብኝ" — ይህ በምግብ ቤት ማወቅ አስፈላጊ ነው።' },

  { de: '═══ ግዢ (Shopping) ═══', am: '🛒 ግዢ ቃላት' },
  { de: 'der Laden / das Geschäft', am: 'Shop / ሱቅ\n\n**Pro Tip:** "Laden" = ሱቅ (ቀላል)፣ "Geschäft" = ሱቅ (መደበኛ)። "Einkaufen gehen" = ግዢ ለመሄድ።' },
  { de: 'der Supermarkt', am: 'Supermarket / ሱፐርማርኬት\n\n**Pro Tip:** ጀርመን ዋና ሱፐርማርኬቶች: Aldi, Lidl (ርካሽ)፣ REWE, Edeka (መካከለኛ)።' },
  { de: 'kaufen / verkaufen', am: 'To buy / To sell / መግዛት / መሸጥ\n\n**Pro Tip:** "Ich möchte das kaufen" = "ይህንን መግዛት እፈልጋለሁ"።' },
  { de: 'der Preis', am: 'Price / ዋጋ\n\n**Pro Tip:** "Was kostet das?" = "ዋጋው ስንት ነው?" ወይም "Wie viel kostet das?"' },
  { de: 'billig / teuer', am: 'Cheap / Expensive / ርካሽ / ውድ\n\n**Pro Tip:** "Das ist zu teuer!" = "ይህ በጣም ውድ ነው!" "Gibt es etwas Billigeres?" = "ርካሽ ነገር አለ?"' },
  { de: 'die Größe', am: 'Size / መጠን\n\n**Pro Tip:** "Welche Größe haben Sie?" = "ምን ያህል መጠን ነው?" — ልብስ ሲገዙ ይጠቅማል።' },
  { de: 'anprobieren', am: 'To try on / መሞከር\n\n**Pro Tip:** "Kann ich das anprobieren?" = "ይህንን ልሞክረው?" — ልብስ ሱቅ ውስጥ ይጠቅማል።' },
  { de: 'die Kasse', am: 'Cash register / ካሳ\n\n**Pro Tip:** "An der Kasse bezahlen" = "ካሳ ላይ መክፈል"።' },
  { de: 'bar / mit Karte', am: 'Cash / By card / በጥሬ / በካርድ\n\n**Pro Tip:** "Bar oder mit Karte?" = "በጥሬ ወይስ በካርድ?" — ይህ ሁልጊዜ ይጠየቃሉ። ጀርመን ውስጥ ብዙ ቦታ ጥሬ ብር ብቻ ነው!!!' },
  { de: 'der Kassenzettel', am: 'Receipt / ደረሰኝ\n\n**Pro Tip:** "Brauchen Sie den Kassenzettel?" = "ደረሰኝ ያስፈልግዎታል?" — ካሳ ላይ ይጠየቃሉ።' },
  { de: 'umtauschen / zurückgeben', am: 'To exchange / To return / መለወጥ / መመለስ\n\n**Pro Tip:** "Kann ich das umtauschen?" = "ይህንን መለወጥ እችላለሁ?" ደረሰኝ ያስፈልጋል!!!' },
  { de: 'der Markt / der Flohmarkt', am: 'Market / Flea market / ገበያ / ጥንታዊ ዕቃ ገበያ\n\n**Pro Tip:** "Flohmarkt" = "ቁንጫ ገበያ" (ቃል በቃል!!) — ያገለገሉ ዕቃዎችን ርካሽ ዋጋ ይሸጣሉ። ቅዳሜ ቅዳሜ ይከፈታል።' },

  { de: '═══ ጉዞ ዓረፍተ ነገሮች (Travel Phrases) ═══', am: '💬 ጉዞ ሙሉ ዓረፍተ ነገሮች' },
  { de: 'Ich bin Tourist.', am: 'I am a tourist. / ቱሪስት ነኝ።\n\n**Pro Tip:** ይህ ዓረፍተ ነገር ችግር ሲገጥምዎት ይጠቅማል — ሰዎች ለመርዳት ፈቃደኛ ይሆናሉ።' },
  { de: 'Sprechen Sie Englisch?', am: 'Do you speak English? / እንግሊዝኛ ይናገራሉ?\n\n**Pro Tip:** ብዙ ጀርመኖች እንግሊዝኛ ያውቃሉ — ግን ጀርመንኛ ለመሞከር ከቻሉ ያደንቁዎታል!!!' },
  { de: 'Ich spreche kein Deutsch.', am: 'I don\'t speak German. / ጀርመንኛ አልናገርም።\n\n**Pro Tip:** "kein" ማለት "ምንም" ማለት ነው — ሰዋስው ደንብ "Negation" ይባላል።' },
  { de: 'Können Sie mir helfen?', am: 'Can you help me? / ልትረዱኝ ይችላሉ?\n\n**Pro Tip:** "Können Sie..." = "ይችላሉ...?" ማለት ጨዋ (polite) ጥያቄ ነው — ይህ ቅርጽ ብዙ ይጠቅማል።' },
  { de: 'Wo kann ich Geld wechseln?', am: 'Where can I exchange money? / ገንዘብ የት ልቀይር?\n\n**Pro Tip:** "Wechselstube" = የገንዘብ ቅያሪ ቦታ። ግን ባንክ ወይም ATM ("Geldautomat") የተሻለ ምጣኔ ይሰጣል።' },
  { de: 'Ich habe mich verlaufen.', am: 'I am lost. / ጠፍቶብኛል።\n\n**Pro Tip:** "sich verlaufen" = ጠፋ (ራስን)። ይህ reflexive verb ነው — "mich" = ራሴን።' },
  { de: 'Rufen Sie bitte die Polizei!', am: 'Please call the police! / ፖሊስ ይደውሉ!\n\n**Pro Tip:** ጀርመን ፖሊስ ቁጥር: 110። የእሳት/አምቡላንስ: 112።' },

  { de: '═══ ቀንና ሳምንት (Days & Time) ═══', am: '📅 ቀንና ሳምንት' },
  { de: 'Montag / Dienstag / Mittwoch', am: 'Monday / Tuesday / Wednesday / ሰኞ / ማክሰኞ / ረቡዕ\n\n**Pro Tip:** "Mittwoch" = "Mitte" (መካከል) + "Woche" (ሳምንት) = "የሳምንቱ መካከል" = ረቡዕ! ቆንጆ ስያሜ!!' },
  { de: 'Donnerstag / Freitag', am: 'Thursday / Friday / ሐሙስ / ዓርብ\n\n**Pro Tip:** "Donnerstag" = "Donner" (ነጎድጓድ) + "Tag" (ቀን) — ከ Norse god Thor ስም የመጣ ነው!!!' },
  { de: 'Samstag / Sonntag', am: 'Saturday / Sunday / ቅዳሜ / እሑድ\n\n**Pro Tip:** "Sonntag" = "Sonne" (ፀሐይ) + "Tag" = "የፀሐይ ቀን"። ጀርመን ውስጥ እሑድ ሱቆች ዝግ ናቸው!!!' },
  { de: 'heute / morgen / gestern', am: 'Today / Tomorrow / Yesterday / ዛሬ / ነገ / ትናንት\n\n**Pro Tip:** "Heute ist Montag" = "ዛሬ ሰኞ ነው"። "Morgen" ጥዋት ማለትም ይሆናል!!' },
  { de: 'die Uhr / die Stunde / die Minute', am: 'Clock / Hour / Minute / ሰዓት / ሰዓት / ደቂቃ\n\n**Pro Tip:** "Wie spät ist es?" = "ስንት ሰዓት ነው?" "Es ist drei Uhr" = "3:00 ነው"።' },
  { de: 'Januar / Februar / März / April', am: 'January / February / March / April\n\n**Pro Tip:** ጀርመንኛ ወራት ከእንግሊዝኛ ጋር ተመሳሳይ ናቸው — ቀላል ነው ለመማር! "Im Januar" = "በጃንዋሪ"።' },
  { de: 'Mai / Juni / Juli / August', am: 'May / June / July / August\n\n**Pro Tip:** "Im Sommer" (በበጋ) = Juni-August. "Im Winter" (በክረምት) = Dezember-Februar.' },
  { de: 'September / Oktober / November / Dezember', am: 'September / October / November / December\n\n**Pro Tip:** "Weihnachten" (ገና) = Dezember 25. "Silvester" (አዲስ ዓመት ዋዜማ) = Dezember 31.' },
  { de: 'der Frühling / der Sommer / der Herbst / der Winter', am: 'Spring / Summer / Autumn / Winter / ፀደይ / በጋ / መኸር / ክረምት\n\n**Pro Tip:** ጀርመን 4 ወቅቶች አሉት — ኢትዮጵያ 2 ዋና ወቅት (ክረምት/በጋ) ስላላት ይህ ልዩነት ለተማሪዎች አስፈላጊ ነው።' },

  { de: '═══ ከተማና ትራንስፖርት (City & Transport) ═══', am: '🏙️ ከተማና ትራንስፖርት ቃላት' },
  { de: 'die Stadt / das Dorf', am: 'City / Village / ከተማ / መንደር\n\n**Pro Tip:** "Großstadt" = ትልቅ ከተማ፣ "Kleinstadt" = ትንሽ ከተማ' },
  { de: 'die Straße / der Platz / die Kreuzung', am: 'Street / Square / Intersection / ጎዳና / አደባባይ / መስቀለኛ\n\n**Pro Tip:** "Straßenbahn" = ትራም — "Straße" + "Bahn" (ባቡር)' },
  { de: 'die Brücke / der Tunnel', am: 'Bridge / Tunnel / ድልድይ / ዋሻ\n\n**Pro Tip:** ጀርመን ብዙ ታሪካዊ ድልድዮች አሉ — "Brücke" ታሪካዊ ቃል ነው!' },
  { de: 'das Rathaus / die Bibliothek', am: 'City hall / Library / ማዘጋጃ ቤት / ቤተ-መጻሕፍት\n\n**Pro Tip:** "Rathaus" = "Rat" (ምክር) + "Haus" (ቤት) = የምክር ቤት = ማዘጋጃ ቤት' },
  { de: 'die Post / die Bank', am: 'Post office / Bank / ፖስታ ቤት / ባንክ\n\n**Pro Tip:** "Deutsche Post" = የጀርመን ፖስታ — ቢጫ ቀለም ምልክት!' },
  { de: 'der Markt / der Supermarkt', am: 'Market / Supermarket / ገበያ / ሱፐርማርኬት\n\n**Pro Tip:** "Wochenmarkt" = ሳምንታዊ ገበያ — ጀርመን ውስጥ ትኩስ ምግብ ያገኛሉ!!' },
  { de: 'die Kirche / die Moschee / der Tempel', am: 'Church / Mosque / Temple / ቤተክርስቲያን / መስጂድ / ቤተመቅደስ\n\n**Pro Tip:** "Dom" = ካቴድራል — ብዙ ጀርመን ከተሞች ታላቅ "Dom" አላቸው (Kölner Dom!)' },
  { de: 'das Museum / das Theater / das Kino', am: 'Museum / Theater / Cinema / ቤተመዘክር / ቴአትር / ሲኒማ\n\n**Pro Tip:** ጀርመን ከዓለም ምርጥ ሙዚየሞች አሉት — በርሊን ብቻ 170+ ሙዚየም!!' },
  { de: 'der Park / der Spielplatz', am: 'Park / Playground / ፓርክ / የልጆች መጫወቻ\n\n**Pro Tip:** "Spiel" = ጨዋታ + "Platz" = ቦታ = "የጨዋታ ቦታ"' },
  { de: 'das Schwimmbad / das Fitnessstudio', am: 'Swimming pool / Gym / መዋኛ / ጂም\n\n**Pro Tip:** "schwimmen" = መዋኘት — ጀርመን ብዙ ሕዝባዊ "Schwimmbäder" አሏት!' },
  { de: 'die U-Bahn / die S-Bahn / die Straßenbahn', am: 'Subway / Urban train / Tram / ሜትሮ / ከተማ ባቡር / ትራም\n\n**Pro Tip:** "U" = Untergrund (ከመሬት ስር)፣ "S" = Schnell (ፈጣን) — ለ commute ወሳኝ!!' },
  { de: 'der Führerschein / die Tankstelle', am: 'Driver\'s license / Gas station / መንጃ ፈቃድ / ቤንዚን ማደያ\n\n**Pro Tip:** ጀርመን ውስጥ "Führerschein" ለማግኘት ~2000€ ያስፈልጋል — ውድ ነው!!' },
  { de: 'der Stau / die Umleitung', am: 'Traffic jam / Detour / ትራፊክ መጨናነቅ / ዙሪያ መንገድ\n\n**Pro Tip:** "Im Stau stehen" = በትራፊክ መጨናነቅ መቆም — "Autobahn" ላይ ይህ ይሆናል' },
  { de: 'der Bürgersteig / die Ampel / der Zebrastreifen', am: 'Sidewalk / Traffic light / Crosswalk / እግር መንገድ / ትራፊክ መብራት / የእግረኛ ማቋረጫ\n\n**Pro Tip:** "Zebrastreifen" = "Zebra" + "Streifen" (ጭረት) — ከዝብራ ስለሚመስል!!' },
  { de: 'die Autobahn / die Geschwindigkeit', am: 'Highway / Speed / ፈጣን መንገድ / ፍጥነት\n\n**Pro Tip:** ጀርመን "Autobahn" ላይ አንዳንድ ቦታ ገደብ የለም — ያለ ገደብ ሊነዱ ይችላሉ!!!' },
  { de: 'parken / tanken / abbiegen', am: 'Park / Refuel / Turn / ማቆም / ቤንዚን መሙላት / ማጠፍ\n\n**Pro Tip:** "links abbiegen" = ወደ ግራ ማጠፍ፣ "rechts abbiegen" = ወደ ቀኝ ማጠፍ' },

  { de: '═══ ገንዘብና ግዢ (Money & Shopping) ═══', am: '💰 ገንዘብ ቃላት' },
  { de: 'der Euro / der Cent', am: 'Euro / Cent / ዩሮ / ሳንቲም\n\n**Pro Tip:** ጀርመን "Euro" (€) ይጠቀማል — 1 Euro = 100 Cent' },
  { de: 'die Kasse / bezahlen / die Quittung', am: 'Cash register / Pay / Receipt / ገንዘብ ቤት / መክፈል / ደረሰኝ\n\n**Pro Tip:** "An der Kasse bezahlen" = ገንዘብ ቤት ላይ መክፈል' },
  { de: 'bar / mit Karte', am: 'Cash / By card / በጥሬ ገንዘብ / በካርድ\n\n**Pro Tip:** ጀርመን ውስጥ ብዙ ቦታ "Nur Barzahlung" (በጥሬ ገንዘብ ብቻ) — ጥሬ ገንዘብ ይዘው ይሂዱ!!' },
  { de: 'das Sonderangebot / der Rabatt', am: 'Special offer / Discount / ልዩ ቅናሽ / ቅናሽ\n\n**Pro Tip:** "Schlussverkauf" = ሽያጭ/ቅናሽ ወቅት — ጃንዋሪ/ጁላይ ውስጥ!!' },
  { de: 'die Größe / die Farbe', am: 'Size / Color / መጠን / ቀለም\n\n**Pro Tip:** "Welche Größe haben Sie?" = "መጠንዎ ስንት ነው?" — ልብስ ሱቅ ውስጥ' },
  { de: 'umtauschen / zurückgeben', am: 'Exchange / Return / መቀየር / መመለስ\n\n**Pro Tip:** "Kann ich das umtauschen?" = "ይህን ልቀይር?" — 14 ቀን ውስጥ ብዙ ጊዜ ይቻላል!' },
  { de: 'die Garantie / die Rechnung', am: 'Warranty / Invoice / ዋስትና / ደረሰኝ\n\n**Pro Tip:** ጀርመን ውስጥ "Rechnung" (ደረሰኝ) ያስቀምጡ — ለመመለስ ያስፈልጋል!' },
];

export const familyVocabulary = [
  { de: '═══ ቤተሰብ (Family Members) ═══', am: '👨‍👩‍👧‍👦 የቤተሰብ ቃላት' },
  { de: 'die Familie', am: 'Family / ቤተሰብ\n\n**Pro Tip:** ጀርመኖች "Kleinfamilie" (ትንሽ ቤተሰብ = እናት/አባት/ልጆች) ይላሉ — ከኢትዮጵያ "ትልቅ ቤተሰብ" (extended family) ባህል ይለያል።' },
  { de: 'der Vater / die Mutter', am: 'Father / Mother / አባት / እናት\n\n**Pro Tip:** "Vater" = ፋተር (ያስታውሱ "V" = "ፍ"!!)። ቀላል: "Papa" / "Mama" ልጆች ይላሉ።' },
  { de: 'der Sohn / die Tochter', am: 'Son / Daughter / ልጅ (ወ) / ልጅ (ሴ)\n\n**Pro Tip:** "Mein Sohn heißt..." = "ልጄ (ወ) ስሙ... ነው"። "Meine Tochter heißt..." = "ልጄ (ሴ) ስሟ... ነው"።' },
  { de: 'der Bruder / die Schwester', am: 'Brother / Sister / ወንድም / እህት\n\n**Pro Tip:** "Geschwister" = ወንድሞችና እህቶች (siblings) — ነጠላ ቃል ሁለቱንም ያካትታል! ይህ በእንግሊዝኛ ለማለት ከባድ ነው ግን ጀርመንኛ ቀላል ያደርገዋል።' },
  { de: 'der Großvater / die Großmutter', am: 'Grandfather / Grandmother / አያት (ወ) / አያት (ሴ)\n\n**Pro Tip:** "Groß" = ትልቅ — "Großvater" = "ትልቅ አባት" = አያት! ቀላል: "Opa" / "Oma" ልጆች ይላሉ (ልክ ኢትዮጵያ "አያቴ" እንደማለት)።' },
  { de: 'der Onkel / die Tante', am: 'Uncle / Aunt / አጎት / አክስት\n\n**Pro Tip:** ኢትዮጵያ ውስጥ "አጎት" ብዙ ሰዎችን ሊያካትት ይችላል ግን ጀርመን ውስጥ "Onkel" = የአባት/እናት ወንድም ብቻ ነው።' },
  { de: 'der Cousin / die Cousine', am: 'Cousin (m) / Cousin (f) / የአጎት/አክስት ልጅ\n\n**Pro Tip:** ከፈረንሳይኛ የተበደረ ቃል ነው — ተመሳሳይ አነባበብ (ኩዛን/ኩዚነ)።' },
  { de: 'der Neffe / die Nichte', am: 'Nephew / Niece / የወንድም/እህት ልጅ (ወ/ሴ)\n\n**Pro Tip:** "Mein Neffe" = "የወንድሜ/እህቴ ልጅ (ወንድ)"።' },
  { de: 'der Schwiegervater / die Schwiegermutter', am: 'Father-in-law / Mother-in-law / አማት / አማት\n\n**Pro Tip:** "Schwieger-" ከማንኛውም የቤተሰብ ቃል ጋር ይጣመራል: "Schwiegersohn" = አማች፣ "Schwiegertochter" = ሚስቱ ቤተሰብ።' },
  { de: 'der Ehemann / die Ehefrau', am: 'Husband / Wife / ባል / ሚስት\n\n**Pro Tip:** "Ehe" = ጋብቻ — "Ehemann" = "የጋብቻ ሰው" = ባል። "Mein Mann" / "Meine Frau" ብለውም ይጠሩአቸዋል (ቀላል)።' },
  { de: 'das Baby / das Kind / der Jugendliche', am: 'Baby / Child / Teenager\n\n**Pro Tip:** ዕድሜ ደረጃ: Baby (0-1) → Kleinkind (1-3) → Kind (3-12) → Jugendlicher (13-17) → Erwachsener (18+).' },
  { de: 'der Freund / die Freundin', am: 'Friend or Boyfriend / Friend or Girlfriend\n\n**Pro Tip:** "Freund/Freundin" ሁለት ትርጉም አለው — ጓደኛ ወይም ፍቅረኛ! ግልጽ ለማድረግ: "ein Freund von mir" = ጓደኛዬ፣ "mein Freund" = ፍቅረኛዬ።' },
  { de: 'ledig / verheiratet / geschieden / verwitwet', am: 'Single / Married / Divorced / Widowed\n\n**Pro Tip:** "Familienstand" = የቤተሰብ ሁኔታ — ቅጾች ላይ ይህ ይጠየቃል። ጀርመን ውስጥ ሁሉንም ሊመርጡ ይችላሉ።' },
  { de: 'schwanger', am: 'Pregnant / ነፍሰ ጡር\n\n**Pro Tip:** "Meine Frau ist schwanger" = "ሚስቴ ነፍሰ ጡር ናት"። "Wann ist der Geburtstermin?" = "መቼ ነው የሚወልዱት?"' },
  { de: 'die Geburt / der Geburtstag', am: 'Birth / Birthday\n\n**Pro Tip:** "Alles Gute zum Geburtstag!" = "ልደትህ/ሽ ይኸን ይብዛ!" — ጀርመኖች ልደት ከመድረሱ በፊት ይገንዛሉ ማለት ክፉ ነው ይላሉ!!!' },
  { de: 'die Hochzeit', am: 'Wedding / ሰርግ\n\n**Pro Tip:** "Hochzeit" = "ከፍተኛ ጊዜ" (ቃል በቃል!)። ጀርመን ሰርግ ሁለት ክፍል አለው: "Standesamt" (ሲቪል) + "kirchliche Trauung" (ቤተክርስቲያን)።' },
  { de: 'das Haustier', am: 'Pet / የቤት እንስሳ\n\n**Pro Tip:** "Haus" = ቤት + "Tier" = እንስሳ — ጀርመኖች እንስሳቶቻቸውን በጣም ይወዳሉ! "Hund" (ውሻ) እና "Katze" (ድመት) በጣም ተወዳጅ ናቸው።' },

  { de: '═══ ስሜቶች (Emotions) ═══', am: '😊 ስሜቶች' },
  { de: 'glücklich / traurig', am: 'Happy / Sad / ደስተኛ / ያዘነ\n\n**Pro Tip:** "Ich bin glücklich" = "ደስተኛ ነኝ"። "Glück" = ዕድል ማለትም ይሆናል! "Viel Glück!" = "መልካም ዕድል!"' },
  { de: 'wütend / ärgerlich', am: 'Angry / Annoyed / ቆጣ / ተበሳጭ\n\n**Pro Tip:** "Ich bin wütend auf dich!" = "ቆጥቶብሃል/ሻል!"' },
  { de: 'müde / energisch', am: 'Tired / Energetic / ደክሞ / ንቁ\n\n**Pro Tip:** "Ich bin so müde" = "በጣም ደክሞኛል" — ብዙ ሰዎች ይህንን ይላሉ!!' },
  { de: 'aufgeregt / nervös', am: 'Excited / Nervous / ፈንጠዝ / ጭንቀት\n\n**Pro Tip:** "Ich bin aufgeregt wegen der Prüfung" = "ፈተናው ስላለ ፈንጠዝ ብሏል/ጨንቆኛል"' },
  { de: 'stolz / beschämt', am: 'Proud / Ashamed / ኩራት / ሀፍረት\n\n**Pro Tip:** "Ich bin stolz auf dich!" = "በአንተ/ሽ ኮርቻለሁ!"' },
  { de: 'einsam / geliebt', am: 'Lonely / Loved / ብቸኛ / ተወዳጅ\n\n**Pro Tip:** "Ich fühle mich einsam" = "ብቸኝነት ይሰማኛል"' },
  { de: 'überrascht / enttäuscht', am: 'Surprised / Disappointed / ተገርሞ / ተስፋ ቆርጦ\n\n**Pro Tip:** "Das hat mich überrascht!" = "ይህ አስደንግጦኛል!"' },
  { de: 'zufrieden / unzufrieden', am: 'Satisfied / Dissatisfied / ረክቶ / ያልረካ\n\n**Pro Tip:** "zu-" = ወደ + "frieden" = ሰላም — "zufrieden" = "ወደ ሰላም" = ረካ! ቆንጆ ቃል!!' },

  { de: '═══ ቤት (House & Home) ═══', am: '🏠 ቤት ቃላት' },
  { de: 'das Haus / die Wohnung', am: 'House / Apartment / ቤት / አፓርትመንት\n\n**Pro Tip:** ጀርመን ውስጥ ብዙ ሰዎች "Wohnung" (ኪራይ ቤት) ውስጥ ይኖራሉ — ቤት መግዛት ውድ ነው!!' },
  { de: 'die Küche', am: 'Kitchen / ማዘጋጃ\n\n**Pro Tip:** "Kuchen" (ኬክ) ≠ "Küche" (ማዘጋጃ) — ኡምላውት ትርጉም ይለውጣል!!' },
  { de: 'das Schlafzimmer', am: 'Bedroom / መኝታ ቤት\n\n**Pro Tip:** "Schlaf" = እንቅልፍ + "Zimmer" = ክፍል — "የእንቅልፍ ክፍል"' },
  { de: 'das Badezimmer', am: 'Bathroom / መታጠቢያ\n\n**Pro Tip:** "Baden" = መታጠብ + "Zimmer" = ክፍል — "የመታጠቢያ ክፍል"' },
  { de: 'das Wohnzimmer', am: 'Living room / መኖሪያ ክፍል\n\n**Pro Tip:** "Wohnen" = መኖር + "Zimmer" = ክፍል — "የመኖሪያ ክፍል"' },
  { de: 'der Garten', am: 'Garden / የአትክልት ቦታ\n\n**Pro Tip:** ጀርመኖች "Schrebergarten" (ትንሽ ክፍት ቦታ) ቤት ውጪ ሄደው ያርሳሉ — ይህ ባህል ነው!!' },
  { de: 'die Miete', am: 'Rent / ኪራይ\n\n**Pro Tip:** "Kaltmiete" = ያለ ወጪዎች ኪራይ፣ "Warmmiete" = ከወጪዎች ጋር — ይህ ልዩነት አስፈላጊ ነው!!' },
  { de: 'der Vermieter / der Mieter', am: 'Landlord / Tenant / ባለቤት / ተከራይ\n\n**Pro Tip:** "vermieten" = ማከራየት፣ "mieten" = መከራየት' },
  { de: 'der Keller / der Dachboden', am: 'Basement / Attic / ምድር ቤት / ጣራ\n\n**Pro Tip:** ጀርመን ቤቶች ብዙ ጊዜ "Keller" (ምድር ቤት) አላቸው — ለማከማቻ ይጠቅማል።' },
  { de: 'die Treppe / der Aufzug', am: 'Stairs / Elevator / ደረጃ / ሊፍት\n\n**Pro Tip:** "Fahrstuhl" ለ "Aufzug" ሌላ ቃል ነው — ሁለቱም ሊፍት ማለት ናቸው።' },
  { de: 'der Nachbar / die Nachbarin', am: 'Neighbor (m/f) / ጎረቤት\n\n**Pro Tip:** "Nachbarschaft" = ሰፈር/ጎረቤትነት — ጀርመን ውስጥ ጎረቤትን ማክበር አስፈላጊ ነው!' },
  { de: 'der Möbel', am: 'Furniture / ቤት ዕቃ\n\n**Pro Tip:** "Möbelhaus" = ቤት ዕቃ ሱቅ — IKEA ጀርመን ውስጥ ታዋቂ ነው!' },
  { de: 'der Tisch / der Stuhl', am: 'Table / Chair / ጠረጴዛ / ወንበር\n\n**Pro Tip:** "Am Tisch sitzen" = ጠረጴዛ ዘንድ መቀመጥ' },
  { de: 'das Bett / das Kissen / die Decke', am: 'Bed / Pillow / Blanket / አልጋ / ትራስ / ብርድ ልብስ\n\n**Pro Tip:** ጀርመኖች "Federbett" (ላባ ብርድ ልብስ) ይወዳሉ!' },
  { de: 'der Schrank / der Kleiderschrank', am: 'Cabinet / Wardrobe / ቁም ሣጥን / ልብስ ቁም ሣጥን\n\n**Pro Tip:** "Kleider" = ልብሶች + "Schrank" = ቁም ሣጥን' },
  { de: 'das Fenster / die Tür', am: 'Window / Door / መስኮት / በር\n\n**Pro Tip:** "Fenster auf!" = መስኮት ክፈት! "Tür zu!" = በር ዝጋ!' },
  { de: 'die Waschmaschine', am: 'Washing machine / ልብስ ማጠቢያ\n\n**Pro Tip:** "Waschen" = ማጠብ + "Maschine" = ማሽን' },
  { de: 'der Kühlschrank', am: 'Refrigerator / ማቀዝቀዣ\n\n**Pro Tip:** "Kühl" = ቀዝቃዛ + "Schrank" = ቁም ሣጥን — "ቀዝቃዛ ቁም ሣጥን"!' },
  { de: 'der Herd / der Ofen', am: 'Stove / Oven / ምድጃ\n\n**Pro Tip:** "Herd" = ምድጃ (ለማብሰል)፣ "Ofen" = ምድጃ (ለማሞቅ/ለመጋገር)' },

  { de: '═══ ሰውነት ክፍሎች (Body Parts) ═══', am: '🏃 ሰውነት ክፍሎች' },
  { de: 'der Kopf', am: 'Head / ጭንቅላት\n\n**Pro Tip:** "Kopfschmerzen" = ራስ ምታት — "Schmerzen" = ህመም' },
  { de: 'das Auge / die Augen', am: 'Eye / Eyes / ዓይን / ዓይኖች\n\n**Pro Tip:** ብዙ ቁጥር: "Auge" → "Augen" — "-n" ይጨምራል' },
  { de: 'das Ohr / die Ohren', am: 'Ear / Ears / ጆሮ / ጆሮዎች\n\n**Pro Tip:** "Ohrenschmerzen" = ጆሮ ህመም' },
  { de: 'die Nase', am: 'Nose / አፍንጫ\n\n**Pro Tip:** "Ich habe Schnupfen" = አፍንጫዬ ተዘግቷል (ጉንፋን)' },
  { de: 'der Mund / die Lippen', am: 'Mouth / Lips / አፍ / ከንፈር\n\n**Pro Tip:** "Mundschutz" = ፊት ጭምብል (Mund = አፍ + Schutz = ጥበቃ)' },
  { de: 'der Zahn / die Zähne', am: 'Tooth / Teeth / ጥርስ / ጥርሶች\n\n**Pro Tip:** "Zahnarzt" = የጥርስ ሐኪም — "Zahn" = ጥርስ + "Arzt" = ሐኪም' },
  { de: 'die Hand / der Finger', am: 'Hand / Finger / እጅ / ጣት\n\n**Pro Tip:** "Handschuh" = ጓንት — "Hand" = እጅ + "Schuh" = ጫማ = "የእጅ ጫማ"!' },
  { de: 'der Fuß / das Knie', am: 'Foot / Knee / እግር / ጉልበት\n\n**Pro Tip:** "Fußball" = እግር ኳስ — ጀርመን ውስጥ በጣም ተወዳጅ ስፖርት!' },
  { de: 'die Schulter / der Rücken', am: 'Shoulder / Back / ትከሻ / ጀርባ\n\n**Pro Tip:** "Rückenschmerzen" = ጀርባ ህመም — ብዙ ሰዎች ይህ ችግር አለባቸው' },
  { de: 'das Herz / die Lunge', am: 'Heart / Lung / ልብ / ሳንባ\n\n**Pro Tip:** "Herzlich willkommen!" = ልባዊ እንኳን ደህና መጡ!' },
  { de: 'der Bauch / der Magen', am: 'Belly / Stomach / ሆድ / ሆድ (ውስጥ)\n\n**Pro Tip:** "Bauch" = ውጪው ሆድ፣ "Magen" = ውስጡ ሆድ (ኦርጋን)' },
  { de: 'das Blut / die Haut', am: 'Blood / Skin / ደም / ቆዳ\n\n**Pro Tip:** "Blutdruck" = ደም ግፊት — "Blut" = ደም + "Druck" = ግፊት' },

  { de: '═══ ቀለሞች (Colors) ═══', am: '🎨 ቀለሞች' },
  { de: 'rot / blau / grün', am: 'Red / Blue / Green / ቀይ / ሰማያዊ / አረንጓዴ\n\n**Pro Tip:** "Die Ampel ist rot" = ትራፊክ መብራት ቀይ ነው' },
  { de: 'gelb / orange / lila', am: 'Yellow / Orange / Purple / ቢጫ / ብርቱካናማ / ወይን ጠጅ\n\n**Pro Tip:** ቀለሞች adjective ናቸው — case ላይ ይቀየራሉ!' },
  { de: 'schwarz / weiß / grau', am: 'Black / White / Gray / ጥቁር / ነጭ / ግራጫ\n\n**Pro Tip:** "Schwarz-Rot-Gold" = የጀርመን ባንዲራ ቀለሞች!' },
  { de: 'braun / rosa / dunkel / hell', am: 'Brown / Pink / Dark / Light / ቡናማ / ሮዛ / ጨለማ / ብሩህ\n\n**Pro Tip:** "dunkelblau" = ጨለማ ሰማያዊ፣ "hellblau" = ብሩህ ሰማያዊ' },

  { de: '═══ ምግብ (Food) ═══', am: '🍕 ምግብ ቃላት' },
  { de: 'das Brot / die Butter / der Käse', am: 'Bread / Butter / Cheese / ዳቦ / ቅቤ / ቀረሮ\n\n**Pro Tip:** ጀርመኖች ከ300+ ዓይነት ዳቦ አላቸው — ዳቦ ባህላቸው ነው!!!' },
  { de: 'das Fleisch / das Hähnchen / der Fisch', am: 'Meat / Chicken / Fish / ሥጋ / ዶሮ / ዓሳ\n\n**Pro Tip:** "Schweinefleisch" = የአሳማ ሥጋ፣ "Rindfleisch" = የበሬ ሥጋ' },
  { de: 'der Reis / die Nudeln / die Kartoffel', am: 'Rice / Noodles / Potato / ሩዝ / ፓስታ / ድንች\n\n**Pro Tip:** ጀርመኖች "Kartoffeln" (ድንች) ብዙ ይበላሉ — ልክ ኢትዮጵያዊ እንጀራ ባህል!' },
  { de: 'das Obst / das Gemüse', am: 'Fruit / Vegetables / ፍራፍሬ / አትክልት\n\n**Pro Tip:** "Obst und Gemüse" = ፍራፍሬና አትክልት — ጤናማ ምግብ!' },
  { de: 'die Milch / der Joghurt / das Ei', am: 'Milk / Yogurt / Egg / ወተት / እርጎ / እንቁላል\n\n**Pro Tip:** "Eier" = እንቁላሎች (ብዙ ቁጥር)' },
  { de: 'der Zucker / das Salz / der Pfeffer', am: 'Sugar / Salt / Pepper / ስኳር / ጨው / በርበሬ\n\n**Pro Tip:** "Salz und Pfeffer" = ጨውና በርበሬ — ሁልጊዜ ጠረጴዛ ላይ ይገኛሉ' },
  { de: 'die Suppe / der Salat', am: 'Soup / Salad / ሾርባ / ሰላጣ\n\n**Pro Tip:** ጀርመንኛ "Suppe" ከላቲን "suppa" የመጣ ነው' },
  { de: 'die Wurst / das Schnitzel', am: 'Sausage / Schnitzel / ቅቤ ስጋ / ሽኒጸል\n\n**Pro Tip:** "Bratwurst" = ጥብስ ቅቤ ስጋ — ታዋቂ የጀርመን ምግብ!!!' },
  { de: 'der Kuchen / die Torte / das Eis', am: 'Cake / Torte / Ice cream / ኬክ / ቶርት / አይስ ክሬም\n\n**Pro Tip:** "Eis" ሁለት ትርጉም: 1) አይስ ክሬም 2) በረዶ!' },
];

export const workVocabulary = [
  { de: '═══ ሥራ (Work & Career) ═══', am: '💼 ሥራ ቃላት' },
  { de: 'die Arbeit / der Job', am: 'Work / Job / ሥራ\n\n**Pro Tip:** "Ich suche Arbeit" = "ሥራ እፈልጋለሁ"። "Arbeit" ይበልጥ መደበኛ ነው፣ "Job" ከእንግሊዝኛ የተበደረ ነው።' },
  { de: 'der Beruf', am: 'Profession / ሙያ\n\n**Pro Tip:** "Was sind Sie von Beruf?" = "ሙያዎ ምንድነው?" — ይህ ጥያቄ ብዙ ይጠየቃል።' },
  { de: 'der Arbeitgeber / der Arbeitnehmer', am: 'Employer / Employee / አሰሪ / ሠራተኛ\n\n**Pro Tip:** "Arbeitgeber" = ሥራ + ሰጪ = "ሥራ ሰጪ"። "Arbeitnehmer" = ሥራ + ተቀባይ = "ሥራ ተቀባይ"። ግልጽ ስያሜ!!' },
  { de: 'das Büro', am: 'Office / ቢሮ\n\n**Pro Tip:** "Ich arbeite im Büro" = "ቢሮ ውስጥ እሰራለሁ"። "Home-Office" = ከቤት መስራት (ጀርመኖች ይህንን ቃል ከእንግሊዝኛ ወሰዱ)።' },
  { de: 'das Gehalt / der Lohn', am: 'Salary / Wages / ደመወዝ\n\n**Pro Tip:** "Gehalt" = ለሠራተኛ ወርሃዊ ደመወዝ፣ "Lohn" = ለሰዓት/ቀን ደመወዝ።' },
  { de: 'die Bewerbung', am: 'Application / ማመልከቻ\n\n**Pro Tip:** "Sich bewerben" = ማመልከት። ጀርመን ውስጥ ማመልከቻ (CV + Anschreiben) መጻፍ ልዩ ሥርዓት አለው!!' },
  { de: 'der Lebenslauf', am: 'CV / Resume / የህይወት ታሪክ\n\n**Pro Tip:** "Leben" = ሕይወት + "Lauf" = ሩጫ/ጉዞ — ቃል በቃል "የሕይወት ጉዞ"! ጀርመን ውስጥ ፎቶ ያለው CV ልማድ ነው (ከአሜሪካ ይለያል)።' },
  { de: 'das Vorstellungsgespräch', am: 'Job interview / ቃለ መጠይቅ\n\n**Pro Tip:** "Vorstellung" = ማስተዋወቅ + "Gespräch" = ንግግር — "ራስን የማስተዋወቅ ንግግር" ማለት ነው!!!' },
  { de: 'der Vertrag', am: 'Contract / ውል\n\n**Pro Tip:** "Arbeitsvertrag" = የሥራ ውል። ጀርመን ውስጥ ሁሉም ሠራተኛ ውል ያስፈልገዋል — ይህ ሕግ ነው።' },
  { de: 'die Kündigung', am: 'Termination / notice / ስንብት\n\n**Pro Tip:** "kündigen" = ሥራ ማቋረጥ/ማባረር። ጀርመን ውስጥ "Kündigungsfrist" (የስንብት ጊዜ) 1-3 ወር ነው!!' },
  { de: 'der Urlaub', am: 'Vacation / ዕረፍት\n\n**Pro Tip:** ጀርመን ውስጥ ሠራተኞች ቢያንስ 20 ቀን ዓመታዊ ዕረፍት ይኖራቸዋል — ብዙ ጊዜ 30 ቀን! ይህ ሕግ ነው!!!' },
  { de: 'die Überstunden', am: 'Overtime / ትርፍ ሰዓት\n\n**Pro Tip:** "Über" = ከ...በላይ + "Stunden" = ሰዓቶች — "ከሰዓት በላይ"። ጀርመኖች ብዙ "Überstunden" አይወዱም!!!' },

  { de: '═══ ሙያዎች (Professions) ═══', am: '👔 ሙያዎች' },
  { de: 'der Arzt / die Ärztin', am: 'Doctor (m/f) / ሐኪም\n\n**Pro Tip:** ጀርመንኛ ብዙ ሙያዎች ወንድ/ሴት ልዩ ቅርጽ አላቸው: "-in" ለሴት ይጨምራል! "Arzt" → "Ärztin"።' },
  { de: 'der Lehrer / die Lehrerin', am: 'Teacher (m/f) / መምህር\n\n**Pro Tip:** ተመሳሳይ: "Lehrer" → "Lehrerin"' },
  { de: 'der Ingenieur / die Ingenieurin', am: 'Engineer / ኢንጂነር\n\n**Pro Tip:** ጀርመን በኢንጂነሪንግ ዝነኛ ናት — "Made in Germany" ብራንድ ዓለም ያውቀዋል!!' },
  { de: 'der Programmierer / die Programmiererin', am: 'Programmer / ፕሮግራመር\n\n**Pro Tip:** "Software-Entwickler" (ሶፍትዌር developer) ብሎም ይባላል። ጀርመን ብዙ IT ሥራ አለ!!' },
  { de: 'der Krankenpfleger / die Krankenschwester', am: 'Nurse (m/f) / ነርስ\n\n**Pro Tip:** "Kranken" = ታማሚ + "Pfleger" = ተንከባካቢ — "ታማሚ ተንከባካቢ"!! ጀርመን ብዙ ነርሶች ያስፈልጋታል — ለኢትዮጵያውያን ሥራ ዕድል!!!' },
  { de: 'der Polizist / die Polizistin', am: 'Police officer / ፖሊስ\n\n**Pro Tip:** "Polizei" = ፖሊስ (ተቋም)። "Polizist" = ፖሊስ (ሰው)።' },
  { de: 'der Koch / die Köchin', am: 'Cook/Chef / ምግብ አብሳይ\n\n**Pro Tip:** "kochen" = ማብሰል → "Koch" = አብሳይ' },
  { de: 'der Soldat / die Soldatin', am: 'Soldier / ወታደር\n\n**Pro Tip:** "Bundeswehr" = የጀርመን ጦር ኃይል — "Bund" = ፌዴሬሽን + "Wehr" = መከላከያ = "የፌዴሬሽን መከላከያ"' },
  { de: 'der Mechaniker / die Mechanikerin', am: 'Mechanic / ሜካኒክ\n\n**Pro Tip:** ጀርመን ብዙ "Ausbildung" (ሙያ ስልጠና) ያስፈልጋል — ከ2-3 ዓመት ስልጠና!!' },
  { de: 'der Rechtsanwalt / die Rechtsanwältin', am: 'Lawyer / ጠበቃ\n\n**Pro Tip:** "Recht" = ሕግ/ቀኝ + "Anwalt" = ወኪል — "የሕግ ወኪል" = ጠበቃ' },
  { de: 'der Architekt / die Architektin', am: 'Architect / አርክቴክት\n\n**Pro Tip:** ከግሪክ ቋንቋ የመጣ — "archi" = ዋና + "tekton" = ሠራተኛ = "ዋና ሠራተኛ/ንድፈ-ሐሳቢ"' },
  { de: 'der Landwirt / der Bauer', am: 'Farmer / ገበሬ\n\n**Pro Tip:** "Land" = ምድር/ሀገር + "Wirt" = ተንከባካቢ — "የምድር ተንከባካቢ" = ገበሬ' },
  { de: 'der Friseur / die Friseurin', am: 'Hairdresser / ፀጉር ሠሪ\n\n**Pro Tip:** ከፈረንሳይኛ "friser" (ፀጉር ማሠራት) የመጣ ቃል' },
  { de: 'der Apotheker / die Apothekerin', am: 'Pharmacist / ፋርማሲስት\n\n**Pro Tip:** "Apotheke" = ፋርማሲ → "Apotheker" = ፋርማሲስት' },
  { de: 'der Pilot / die Pilotin', am: 'Pilot / አብራሪ\n\n**Pro Tip:** "Pilot" ዓለም ዓቀፍ ቃል ነው — ሁሉም ቋንቋ ይጠቀማል!' },
  { de: 'der Fahrer / die Fahrerin', am: 'Driver / ሹፌር\n\n**Pro Tip:** "Taxifahrer" = ታክሲ ሹፌር፣ "Busfahrer" = ባስ ሹፌር' },
  { de: 'der Kellner / die Kellnerin', am: 'Waiter/Waitress / አስተናጋጅ\n\n**Pro Tip:** "Herr Ober!" ብሎም ይጠራሉ (ለወንድ)' },
  { de: 'der Journalist / die Journalistin', am: 'Journalist / ጋዜጠኛ\n\n**Pro Tip:** "Zeitung" = ጋዜጣ — "Zeitungsjournalist" = የጋዜጣ ጋዜጠኛ' },
  { de: 'der Wissenschaftler / die Wissenschaftlerin', am: 'Scientist / ሳይንቲስት\n\n**Pro Tip:** "Wissenschaft" = ሳይንስ = "Wissen" (ዕውቀት) + "Schaft" (ዘርፍ)' },
  { de: 'der Musiker / die Musikerin', am: 'Musician / ሙዚቀኛ\n\n**Pro Tip:** "Musik machen" = ሙዚቃ መሥራት/መጫወት' },
  { de: 'der Künstler / die Künstlerin', am: 'Artist / ሥዕል ሰዓሊ\n\n**Pro Tip:** "Kunst" = ኪነ-ጥበብ → "Künstler" = አርቲስት' },
  { de: 'der Zahnarzt / die Zahnärztin', am: 'Dentist / የጥርስ ሐኪም\n\n**Pro Tip:** "Zahn" = ጥርስ + "Arzt" = ሐኪም' },

  { de: '═══ ትምህርት (Education) ═══', am: '📚 ትምህርት ቃላት' },
  { de: 'die Schule / die Universität', am: 'School / University / ትምህርት ቤት / ዩኒቨርሲቲ\n\n**Pro Tip:** ጀርመን ውስጥ ዩኒቨርሲቲ ነፃ ነው (በብዙ ግዛቶች)! "Studiengebühren" = ትምህርት ክፍያ — ብዙ ጊዜ ዝቅተኛ!!' },
  { de: 'der Schüler / der Student', am: 'Student (school) / Student (uni) / ተማሪ\n\n**Pro Tip:** "Schüler" = ትምህርት ቤት ተማሪ፣ "Student" = ዩኒቨርሲቲ ተማሪ — ልዩነት አለ!' },
  { de: 'die Prüfung / die Klausur', am: 'Exam / Written exam / ፈተና\n\n**Pro Tip:** "Ich habe eine Prüfung" = "ፈተና አለብኝ"' },
  { de: 'die Hausaufgabe', am: 'Homework / የቤት ሥራ\n\n**Pro Tip:** "Haus" = ቤት + "Aufgabe" = ተግባር — "የቤት ተግባር"' },
  { de: 'das Zeugnis', am: 'Report card / Certificate / ምስክር ወረቀት\n\n**Pro Tip:** ጀርመን ውስጥ ሥራ ለመቀጠር "Zeugnis" (ሰርተፍኬት) ወሳኝ ነው!!' },
  { de: 'die Note / die Bewertung', am: 'Grade / Evaluation / ደረጃ\n\n**Pro Tip:** ጀርመን ደረጃ: 1 = በጣም ጥሩ (ምርጥ)... 6 = ደካማ (ወደቀ)' },
  { de: 'das Praktikum / die Ausbildung', am: 'Internship / Vocational training / ልምምድ / ሙያ ስልጠና\n\n**Pro Tip:** ጀርመን ውስጥ "Ausbildung" ቅድሚያ ይሰጣል — ሙያ ማወቅ ዩኒቨርሲቲ ያህል ይከበራል!!' },
  { de: 'der Kindergarten', am: 'Kindergarten / ልጆች ማቆያ\n\n**Pro Tip:** ይህ ቃል ጀርመንኛ ነው — ዓለም ሁሉ ይጠቀማል! "Kinder" = ልጆች + "Garten" = አትክልት ቦታ' },

  { de: '═══ ቴክኖሎጂ (Technology) ═══', am: '💻 ቴክኖሎጂ ቃላት' },
  { de: 'der Computer / der Laptop', am: 'Computer / Laptop / ኮምፒውተር\n\n**Pro Tip:** "Rechner" ብሎም ይባላል — "rechnen" = ማስላት' },
  { de: 'das Handy / das Smartphone', am: 'Mobile phone / Smartphone / ሞባይል\n\n**Pro Tip:** "Handy" ጀርመኖች ብቻ የሚጠቀሙበት ቃል ነው — እንግሊዝኛ ተናጋሪ "handy" ቢሰማ ግራ ይገባዋል!!' },
  { de: 'das Internet / das WLAN', am: 'Internet / WiFi / ኢንተርኔት / ዋይፋይ\n\n**Pro Tip:** "Haben Sie WLAN?" = "ዋይፋይ አለዎት?" — ይህ ጥያቄ ብዙ ይጠየቃል! "WLAN" = "Veh-Lahn" ይነበባል!' },
  { de: 'das Passwort', am: 'Password / ፓስዋርድ\n\n**Pro Tip:** "Wie ist das Passwort?" = "ፓስዋርዱ ምንድነው?"' },
  { de: 'die App / die Software', am: 'App / Software / መተግበሪያ\n\n**Pro Tip:** "Laden Sie die App herunter" = "መተግበሪያውን ያውርዱ"' },
  { de: 'die E-Mail / die Nachricht', am: 'Email / Message / ኢ-ሜይል / መልዕክት\n\n**Pro Tip:** "Schicken Sie mir eine E-Mail" = "ኢ-ሜይል ይላኩልኝ"' },
  { de: 'drucken / speichern / löschen', am: 'Print / Save / Delete / ማተም / ማስቀመጥ / መሰረዝ\n\n**Pro Tip:** "Strg + S" = speichern (ማስቀመጥ)! ኮምፒውተር ላይ ጠቃሚ!!' },

  { de: '═══ ጊዜ (Time) ═══', am: '⏰ ጊዜ ቃላት' },
  { de: 'die Stunde / die Minute / die Sekunde', am: 'Hour / Minute / Second / ሰዓት / ደቂቃ / ሰከንድ\n\n**Pro Tip:** "Wie viel Uhr ist es?" = "ስንት ሰዓት ነው?"' },
  { de: 'heute / morgen / gestern', am: 'Today / Tomorrow / Yesterday / ዛሬ / ነገ / ትናንት\n\n**Pro Tip:** "morgen" (ነገ) ≠ "der Morgen" (ጠዋት) — ዝቅ/ትልቅ ፊደል ትርጉም ይለውጣል!' },
  { de: 'jetzt / später / früher', am: 'Now / Later / Earlier / አሁን / በኋላ / ቀደም\n\n**Pro Tip:** "Bis später!" = "ቻው! በኋላ እንገናኝ!"' },
  { de: 'der Montag / der Dienstag / der Mittwoch', am: 'Monday / Tuesday / Wednesday / ሰኞ / ማክሰኞ / ረቡዕ\n\n**Pro Tip:** "Mittwoch" = "Mitte" (መካከል) + "Woche" (ሳምንት) — "የሳምንት መካከል"!' },
  { de: 'der Donnerstag / der Freitag / der Samstag / der Sonntag', am: 'Thursday / Friday / Saturday / Sunday / ሐሙስ / ዓርብ / ቅዳሜ / እሑድ\n\n**Pro Tip:** "Donnerstag" = "Donner" (ነጎድጓድ) ቀን — ከ Norse ባህል!' },
  { de: 'der Januar / der Februar / der März', am: 'January / February / March / ጥር / የካቲት / መጋቢት\n\n**Pro Tip:** ጀርመንኛ ወራት ከላቲን/ሮማን ቋንቋ የመጡ ናቸው' },
  { de: 'der Frühling / der Sommer / der Herbst / der Winter', am: 'Spring / Summer / Autumn / Winter / ጸደይ / ክረምት / መፀው / ቅዝቃዜ\n\n**Pro Tip:** ጀርመን ውስጥ 4 ወቅቶች ግልጽ ናቸው — ኢትዮጵያ ውስጥ ከምናውቀው ይለያል!' },
];

export const emergencyVocabulary = [
  { de: '═══ ድንገተኛ ሁኔታ (Emergency) ═══', am: '🚨 ድንገተኛ ሁኔታ' },
  { de: 'Hilfe! / Hilfe, bitte!', am: 'Help! / Help, please! / እርዳታ!\n\n**Pro Tip:** ይህ በጣም አስፈላጊ ቃል ነው — "HILFE!" ብለው ጮሁ!! ማንም ቦታ ቢሆኑ ሰዎች ይረዱዎታል።' },
  { de: 'Notruf 112', am: 'Emergency number 112 / የድንገተኛ ጊዜ ቁጥር 112\n\n**Pro Tip:** 112 = ለእሳት + አምቡላንስ + ድንገተኛ። 110 = ለፖሊስ ብቻ። 112 በመላ አውሮፓ ይሠራል!!!!' },
  { de: 'der Krankenwagen / die Ambulanz', am: 'Ambulance / አምቡላንስ\n\n**Pro Tip:** "Kranken" = ታማሚ + "Wagen" = መኪና — "የታማሚ መኪና" = አምቡላንስ' },
  { de: 'die Feuerwehr', am: 'Fire department / እሳት አጥፊ\n\n**Pro Tip:** "Feuer" = እሳት + "Wehr" = መከላከያ — "የእሳት መከላከያ"' },
  { de: 'die Polizei', am: 'Police / ፖሊስ\n\n**Pro Tip:** "Rufen Sie die Polizei!" = "ፖሊስ ይደውሉ!" 110 ይደውሉ።' },
  { de: 'das Krankenhaus', am: 'Hospital / ሆስፒታል\n\n**Pro Tip:** "Kranken" = ታማሚ + "Haus" = ቤት — "የታማሚ ቤት" = ሆስፒታል' },
  { de: 'die Apotheke', am: 'Pharmacy / ፋርማሲ\n\n**Pro Tip:** ጀርመን ውስጥ መድሃኒት ለመግዛት ፋርማሲ (Apotheke) መሄድ ግዴታ ነው — ሱፐርማርኬት ውስጥ አይሸጡም!! አረንጓዴ ምልክት ("A") ላይ ይፈልጉ።' },
  { de: 'der Arzt / die Notaufnahme', am: 'Doctor / Emergency room / ሐኪም / ድንገተኛ ክፍል\n\n**Pro Tip:** "Notaufnahme" = "Not" (ድንገተኛ) + "Aufnahme" (ተቀባይ) — ሆስፒታል ድንገተኛ ክፍል።' },
  { de: 'Ich brauche einen Arzt!', am: 'I need a doctor! / ሐኪም ያስፈልገኛል!\n\n**Pro Tip:** ይህ ዓረፍተ ነገር ለደህንነትዎ ወሳኝ ነው — ያስታውሱት!!' },
  { de: 'Ich bin krank.', am: 'I am sick. / ታምሜአለሁ።\n\n**Pro Tip:** "krank" = ታማሚ። "Ich habe Fieber" = "ትኩሳት አለብኝ"። "Ich habe Kopfschmerzen" = "ራስ ምታት አለብኝ"።' },
  { de: 'Ich bin verletzt.', am: 'I am injured. / ቆስያለሁ።\n\n**Pro Tip:** "verletzt" = ቁስል ያለበት። "Wo sind Sie verletzt?" = "የት ነው ቁስሉ?"' },
  { de: 'Es tut weh! / Ich habe Schmerzen.', am: 'It hurts! / I have pain. / ያመኛል!\n\n**Pro Tip:** ሐኪሙ "Wo tut es weh?" = "የት ነው ያመዎት?" ይላል።' },
  { de: 'der Kopf / der Bauch / das Herz', am: 'Head / Stomach / Heart / ጭንቅላት / ሆድ / ልብ\n\n**Pro Tip:** "Kopfschmerzen" = ራስ ምታት፣ "Bauchschmerzen" = ሆድ ህመም፣ "Herzschmerzen" = ልብ ህመም — "-schmerzen" = ህመም!!' },
  { de: 'der Arm / das Bein / der Rücken', am: 'Arm / Leg / Back / እጅ / እግር / ጀርባ\n\n**Pro Tip:** "Ich habe Rückenschmerzen" = "ጀርባዬ ያመኛል"' },
  { de: 'die Allergie / die Medizin / das Rezept', am: 'Allergy / Medicine / Prescription\n\n**Pro Tip:** "Ich bin allergisch gegen..." = "ለ... አለርጂ አለብኝ"። ጀርመን ውስጥ ብዙ መድሃኒት "Rezept" (ማዘዣ) ያስፈልጋል!' },
  { de: 'Feuer! / Es brennt!', am: 'Fire! / It\'s burning! / እሳት!\n\n**Pro Tip:** "FEUER!" ብለው ጮሁ!! 112 ይደውሉ!! "Es brennt im Haus!" = "ቤቱ ውስጥ እሳት ይቃጠላል!"' },
  { de: 'der Dieb / der Überfall', am: 'Thief / Robbery / ሌባ / ዘረፋ\n\n**Pro Tip:** "Haltet den Dieb!" = "ሌባውን ያዙ!" "Ich wurde bestohlen" = "ተዘርፌአለሁ"' },
  { de: 'der Unfall', am: 'Accident / አደጋ\n\n**Pro Tip:** "Es gab einen Unfall" = "አደጋ ተከስቷል"። "Autounfall" = የመኪና አደጋ' },
  { de: 'die Versicherung', am: 'Insurance / ኢንሹራንስ\n\n**Pro Tip:** ጀርመን ውስጥ "Krankenversicherung" (የጤና ኢንሹራንስ) ግዴታ ነው — ሁሉም ሰው ሊኖረው ይገባል!!! "Haftpflichtversicherung" (የአደጋ ኢንሹራንስ) ምክር ነው።' },
  { de: 'Ich brauche Hilfe! Es ist dringend!', am: 'I need help! It\'s urgent!\n\n**Pro Tip:** "dringend" = አስቸኳይ — ይህ ቃል ያከብራሉ ሰዎች ፈጣን ምላሽ ይሰጣሉ!!' },

  { de: '═══ ሕግ (Legal) ═══', am: '⚖️ ሕግ ቃላት' },
  { de: 'der Ausweis / der Personalausweis', am: 'ID / Personal ID / መታወቂያ\n\n**Pro Tip:** "Ihren Ausweis, bitte!" = "መታወቂያዎን እባክዎ!" — ፖሊስ ይህ ይጠይቃል።' },
  { de: 'die Botschaft / das Konsulat', am: 'Embassy / Consulate / ኤምባሲ / ቆንስላ\n\n**Pro Tip:** "Äthiopische Botschaft" = የኢትዮጵያ ኤምባሲ — Berlin ውስጥ ይገኛል!!!' },
  { de: 'der Anwalt', am: 'Lawyer / ጠበቃ\n\n**Pro Tip:** "Ich möchte einen Anwalt sprechen" = "ጠበቃ ማናገር እፈልጋለሁ" — ይህ መብትዎ ነው!!' },
  { de: 'die Anzeige erstatten', am: 'To file a report / ጥቆማ ማቅረብ\n\n**Pro Tip:** "Ich möchte eine Anzeige erstatten" = "ጥቆማ ማቅረብ እፈልጋለሁ" — ፖሊስ ጣቢያ ይህ ይላሉ' },
  { de: 'das Formular / das Dokument', am: 'Form / Document / ቅጽ / ሰነድ\n\n**Pro Tip:** "Füllen Sie dieses Formular aus" = "ይህንን ቅጽ ይሙሉ"' },
  { de: 'das Visum / die Aufenthaltserlaubnis', am: 'Visa / Residence permit / ቪዛ / የመኖሪያ ፈቃድ\n\n**Pro Tip:** "Aufenthalt" = ቆይታ + "Erlaubnis" = ፈቃድ — ጀርመን ውስጥ ይህ ሰነድ ወሳኝ ነው!!' },
  { de: 'das Asyl / der Flüchtling', am: 'Asylum / Refugee / ጥገኝነት / ስደተኛ\n\n**Pro Tip:** "Asylbewerber" = ጥገኝነት ጠያቂ — "Asyl" + "Bewerber" (ጠያቂ)' },
  { de: 'die Aufenthaltsgenehmigung', am: 'Residence permit / የቆይታ ፈቃድ\n\n**Pro Tip:** "Genehmigung" = ፈቃድ — ይህ ከ "Erlaubnis" ጋር ተመሳሳይ ነው' },
  { de: 'der Dolmetscher / die Dolmetscherin', am: 'Interpreter / አስተርጓሚ\n\n**Pro Tip:** "Ich brauche einen Dolmetscher" = "አስተርጓሚ ያስፈልገኛል"' },
  { de: 'die Strafe / das Bußgeld', am: 'Penalty / Fine / ቅጣት / መቀጮ\n\n**Pro Tip:** "Strafzettel" = የቅጣት ወረቀት — ለትራፊክ ጥሰት ይሰጣል' },
  { de: 'verboten / erlaubt', am: 'Forbidden / Allowed / ክልክል / ተፈቅዷል\n\n**Pro Tip:** "Rauchen verboten!" = "ማጨስ ክልክል!"' },
  { de: 'die Gefahr / gefährlich', am: 'Danger / Dangerous / አደጋ / አደገኛ\n\n**Pro Tip:** "Lebensgefahr!" = "የህይወት አደጋ!" — ይህ ማስጠንቀቂያ ምልክት ላይ ይገኛል' },
  { de: 'der Notausgang', am: 'Emergency exit / ድንገተኛ መውጫ\n\n**Pro Tip:** "Not" = ድንገተኛ + "Ausgang" = መውጫ — አረንጓዴ ምልክት ለይ ይፈልጉ!' },
  { de: 'die Erste Hilfe', am: 'First aid / የመጀመሪያ እርዳታ\n\n**Pro Tip:** ጀርመን ውስጥ "Erste-Hilfe-Kurs" (የመጀመሪያ ዕርዳታ ኮርስ) ለመንጃ ፈቃድ ግዴታ ነው!!' },
  { de: 'das Gift / giftig', am: 'Poison / Toxic / መርዝ / መርዛም\n\n**Pro Tip:** "Vorsicht, giftig!" = "ተጠንቀቁ፣ መርዝ!" — ይህ ምልክት ውጪ ማየት ይቻላል' },
  { de: 'der Herzinfarkt / der Schlaganfall', am: 'Heart attack / Stroke / የልብ ድንገተኛ / ስትሮክ\n\n**Pro Tip:** ምልክቶች: ደረት ህመም (Herzinfarkt)፣ ድንገት ማዞር/ማሳከክ (Schlaganfall) — ወዲያው 112 ይደውሉ!!' },
  { de: 'die Blutung / die Wunde', am: 'Bleeding / Wound / ደም ፍሰት / ቁስል\n\n**Pro Tip:** "Die Blutung stoppen" = "ደም ፍሰቱን ማቆም"' },
  { de: 'bewusstlos / ohnmächtig', am: 'Unconscious / Fainted / ራሱን ስቶ\n\n**Pro Tip:** "Er ist bewusstlos!" = "ራሱን ስቷል!" — 112 ይደውሉ' },
  { de: 'die Überschwemmung / das Erdbeben', am: 'Flood / Earthquake / ጎርፍ / የመሬት መንቀጥቀጥ\n\n**Pro Tip:** "Erdbeben" = "Erde" (ምድር) + "beben" (መንቀጥቀጥ)' },
  { de: 'evakuieren / fliehen', am: 'Evacuate / Flee / ማስወጣት / ማምለጥ\n\n**Pro Tip:** "Wir müssen evakuieren!" = "መውጣት አለብን!"' },
  { de: 'der Feuerlöscher', am: 'Fire extinguisher / እሳት ማጥፊያ\n\n**Pro Tip:** "Feuer" = እሳት + "Löscher" = ማጥፊያ — ሁሉም ሕንፃ ውስጥ ይገኛል!!' },

  { de: '═══ ጤና (Health & Medical) ═══', am: '🏥 ጤና ቃላት' },
  { de: 'die Gesundheit / die Krankheit', am: 'Health / Illness / ጤና / ህመም\n\n**Pro Tip:** "Gesundheit!" — ጀርመኖች አንድ ሰው ሲያስነጥስ ይህ ይላሉ (= ጤና ይስጥልኝ)!' },
  { de: 'der Husten / der Schnupfen / das Fieber', am: 'Cough / Cold / Fever / ሳል / ጉንፋን / ትኩሳት\n\n**Pro Tip:** "Ich habe Husten und Schnupfen" = ሳልና ጉንፋን አለብኝ' },
  { de: 'die Tablette / die Spritze / die Salbe', am: 'Pill / Injection / Ointment / ክኒን / መርፌ / ቅባት\n\n**Pro Tip:** "eine Tablette nehmen" = ክኒን መውሰድ' },
  { de: 'der Zahnarzt / der Augenarzt / der Hautarzt', am: 'Dentist / Eye doctor / Dermatologist / የጥርስ ሐኪም / የዓይን ሐኪም / የቆዳ ሐኪም\n\n**Pro Tip:** ጀርመንኛ ልዩ ሐኪሞች: "Fach" (ልዩ) + "Arzt" (ሐኪም) = "Facharzt" (ስፔሻሊስት)' },
  { de: 'der Termin / die Sprechstunde', am: 'Appointment / Office hours / ቀጠሮ / የስራ ሰዓት\n\n**Pro Tip:** "Ich möchte einen Termin machen" = ቀጠሮ ማስያዝ እፈልጋለሁ' },
  { de: 'die Operation / die Untersuchung', am: 'Surgery / Examination / ቀዶ ጥገና / ምርመራ\n\n**Pro Tip:** "Blutuntersuchung" = የደም ምርመራ' },
  { de: 'die Impfung / die Blutprobe', am: 'Vaccination / Blood test / ክትባት / የደም ናሙና\n\n**Pro Tip:** ጀርመን ውስጥ ክትባት ነፃ ነው — ሕዝባዊ ጤና ኢንሹራንስ ይሸፍናል!' },
  { de: 'schwanger / die Entbindung', am: 'Pregnant / Delivery / ነፍሰ ጡር / ወሊድ\n\n**Pro Tip:** "Entbindungsstation" = ወሊድ ክፍል' },
  { de: 'der Rollstuhl / die Krücke', am: 'Wheelchair / Crutch / የሽክር ወንበር / ክራንች\n\n**Pro Tip:** "Barrierefreiheit" = ተደራሽነት — ጀርመን ብዙ ቦታ wheelchair-friendly ነው!' },
  { de: 'die Atmung / der Puls / der Blutdruck', am: 'Breathing / Pulse / Blood pressure / ትንፋሽ / ልብ ምት / ደም ግፊት\n\n**Pro Tip:** "Bluthochdruck" = ከፍተኛ ደም ግፊት፣ "Blutniedrigdruck" = ዝቅተኛ ደም ግፊት' },
  { de: 'die Physiotherapie / die Rehabilitation', am: 'Physical therapy / Rehabilitation / ፊዚዮቴራፒ / ማገገሚያ\n\n**Pro Tip:** ጀርመን ውስጥ "Reha" (ማገገሚያ) ለብዙ ህመሞች ይቻላል — ኢንሹራንስ ይሸፍናል!' },
  { de: 'der Krankenschein / die Arbeitsunfähigkeit', am: 'Sick note / Inability to work / የህመም ማረጋገጫ / ስራ መስራት አለመቻል\n\n**Pro Tip:** ጀርመን ውስጥ ከ3 ቀን በላይ ከታመሙ "Krankenschein" (ከሐኪም ማረጋገጫ) ለሥራ ማቅረብ ግዴታ!!' },

  { de: '═══ ስሜትና ባሕሪ (Feelings & Character) ═══', am: '😊 ስሜትና ባሕሪ' },
  { de: 'freundlich / höflich / ehrlich', am: 'Friendly / Polite / Honest / ተግባቢ / ትሁት / ታማኝ\n\n**Pro Tip:** ጀርመኖች "Pünktlichkeit" (ሰዓት ጠባቂነት) ባህል ነው — ሁልጊዜ በሰዓት ይድረሱ!!' },
  { de: 'fleißig / faul / neugierig', am: 'Hardworking / Lazy / Curious / ታታሪ / ሰነፍ / ጠያቂ\n\n**Pro Tip:** "fleißig" ጀርመን ውስጥ ከፍ ያለ ውዳሴ ነው — ታታሪነት ይከበራል!' },
  { de: 'mutig / ängstlich / schüchtern', am: 'Brave / Anxious / Shy / ድፍር / ፈሪ / አፋር\n\n**Pro Tip:** "Mut" = ድፍረት — "Mut haben" = ድፍረት ማግኘት' },
  { de: 'geduldig / ungeduldig / ruhig', am: 'Patient / Impatient / Calm / ታጋሽ / ቁጡ / ረጋ ያለ\n\n**Pro Tip:** "un-" ቅድመ ቃል ተቃራኒ ያደርጋል: "geduldig" → "ungeduldig"' },
  { de: 'intelligent / dumm / kreativ', am: 'Intelligent / Stupid / Creative / ብልጥ / ሞኝ / ፈጠራኛ\n\n**Pro Tip:** "klug" = ብልጥ (ሌላ ቃል) — "ein kluger Kopf" = ብልጥ ጭንቅላት' },
  { de: 'romantisch / humorvoll / ernst', am: 'Romantic / Humorous / Serious / ሮማንቲክ / ቀልደኛ / ከባድ\n\n**Pro Tip:** ጀርመኖች "ernst" (ከባድ) ሲባሉ ይከፋሉ — ቀልድ ይወዳሉ!' },
  { de: 'das Vertrauen / die Hoffnung / der Traum', am: 'Trust / Hope / Dream / እምነት / ተስፋ / ሕልም\n\n**Pro Tip:** "Ich habe einen Traum" = ሕልም አለኝ — ይህ ዓረፍተ ነገር ተነሳሽ ነው!!' },

  { de: '═══ የአየር ሁኔታ (Weather) ═══', am: '🌤️ የአየር ሁኔታ' },
  { de: 'die Sonne / der Regen / der Schnee', am: 'Sun / Rain / Snow / ፀሐይ / ዝናብ / በረዶ\n\n**Pro Tip:** "Es regnet" = ዝናብ ይዘንባል፣ "Es schneit" = በረዶ ይወርዳል' },
  { de: 'der Wind / der Sturm / das Gewitter', am: 'Wind / Storm / Thunderstorm / ነፋስ / ዐውሎ / ነጎድጓድ\n\n**Pro Tip:** "Unwetter" = መጥፎ ሁኔታ — "Un-" = ክፉ/መጥፎ' },
  { de: 'warm / kalt / heiß / kühl', am: 'Warm / Cold / Hot / Cool / ሙቅ / ቀዝቃዛ / ትኩስ / መጠነኛ\n\n**Pro Tip:** "Es ist heiß draußen" = ውጪ ትኩስ ነው' },
  { de: 'der Nebel / das Eis / die Wolke', am: 'Fog / Ice / Cloud / ጭጋግ / በረዶ / ደመና\n\n**Pro Tip:** "neblig" = ጭጋጋማ — "Vorsicht, es ist neblig!" = ተጠንቀቁ ጭጋግ ነው!' },
  { de: 'die Temperatur / der Grad', am: 'Temperature / Degree / ሙቀት / ዲግሪ\n\n**Pro Tip:** ጀርመን Celsius (°C) ይጠቀማል — 0°C = መቀዝቀዝ ነጥብ!' },
  { de: 'der Regenschirm / die Jacke / der Mantel', am: 'Umbrella / Jacket / Coat / ጃንጥላ / ጃኬት / ካፖርት\n\n**Pro Tip:** ጀርመን ውስጥ "Regenschirm" ሁልጊዜ ይዘው ይሂዱ — አየር ይቀያየራል!' },
];
